In [227]:
from rdkit import Chem
import pandas as pd
from rdkit.Chem import PandasTools
import os
from rdkit import RDConfig
import itertools

In [247]:
sdfFile = os.path.join(RDConfig.RDDataDir,'/g/zimmermann/Members/zulfiqar/ZM000_PistoiaPrj/GutMicrobiome/myCompounds.sdf')

In [248]:
frame = PandasTools.LoadSDF(sdfFile, includeFingerprints=True)

In [249]:
frame = frame[~frame.ID.str.contains("TROSPIUM_CHLORIDE")]
frame = frame[~frame.ID.str.contains("QUINACRINE")]
frame = frame[~frame.ID.str.contains("DIGITOXIN")]
frame = frame[~frame.ID.str.contains("DIGOXIN")]

In [250]:
frame

                       ID                                             ROMol
0              BUDESONIDE  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf19af0>
1               BUPROPION  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf19fc0>
2                BURAMATE  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf19850>
3               BUSPIRONE  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf1a180>
4        ABACAVIR_SULFATE  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf19d20>
..                    ...                                               ...
270              WARFARIN  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf40900>
271              ZALEPLON  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf409e0>
272       ZIDOVUDINE__AZT  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf40ac0>
273  ZIPRASIDONE_MESYLATE  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf40ba0>
274              ZOLPIDEM  <rdkit.Chem.rdchem.Mol object at 0x7fafbdf40c80>

[271 rows x 2 columns]

In [251]:
ID = ["BETAMETHASONE", "DIHYDROERGOTAMINE_MESYLATE", "MESORIDAZINE_BESYLATE", "ARIPIPRAZOLE", "PROCHLORPERAZINE_EDISYLATE"]
SMILES = ["CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C",
"CC1(C(=O)N2C(C(=O)N3CCCC3C2(O1)O)CC4=CC=CC=C4)NC(=O)C5CC6C(CC7=CNC8=CC=CC6=C78)N(C5)C.CS(=O)(=O)O",
"CN1CCCCC1CCN2C3=CC=CC=C3SC4=C2C=C(C=C4)S(=O)C.C1=CC=C(C=C1)S(=O)(=O)O",
"C1CC(=O)NC2=C1C=CC(=C2)OCCCCN3CCN(CC3)C4=C(C(=CC=C4)Cl)Cl",
"CN1CCN(CC1)CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)Cl.C(CS(=O)(=O)O)S(=O)(=O)O"]

In [252]:
ROMol = [Chem.MolFromSmiles(i) for i in SMILES]

In [253]:
df2 = pd.DataFrame(list(zip(ID, ROMol)), columns=['ID', 'ROMol'])

In [254]:
df2

,ID,ROMol
0,BETAMETHASONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19150>
1,DIHYDROERGOTAMINE_MESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a80>
2,MESORIDAZINE_BESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45930>
3,ARIPIPRAZOLE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf459a0>
4,PROCHLORPERAZINE_EDISYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a10>

In [255]:
frames = [frame, df2]
result = pd.concat(frames, ignore_index=True)

In [256]:
result

,ID,ROMol
0,BUDESONIDE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19af0>
1,BUPROPION,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19fc0>
2,BURAMATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19850>
3,BUSPIRONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf1a180>
4,ABACAVIR_SULFATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19d20>
...,...,...
271,BETAMETHASONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19150>
272,DIHYDROERGOTAMINE_MESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a80>
273,MESORIDAZINE_BESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45930>
274,ARIPIPRAZOLE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf459a0>
275,PROCHLORPERAZINE_EDISYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a10>

In [257]:
frame = result

In [258]:
frame

,ID,ROMol
0,BUDESONIDE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19af0>
1,BUPROPION,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19fc0>
2,BURAMATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19850>
3,BUSPIRONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf1a180>
4,ABACAVIR_SULFATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19d20>
...,...,...
271,BETAMETHASONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19150>
272,DIHYDROERGOTAMINE_MESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a80>
273,MESORIDAZINE_BESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45930>
274,ARIPIPRAZOLE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf459a0>
275,PROCHLORPERAZINE_EDISYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a10>

In [259]:
import pubchempy as pcp

In [260]:
frame["ID_pubchem"] = [f.replace("_", " ") for f in frame["ID"]]

In [261]:
frame

,ID,ROMol,ID_pubchem
0,BUDESONIDE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19af0>,BUDESONIDE
1,BUPROPION,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19fc0>,BUPROPION
2,BURAMATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19850>,BURAMATE
3,BUSPIRONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf1a180>,BUSPIRONE
4,ABACAVIR_SULFATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19d20>,ABACAVIR SULFATE
...,...,...,...
271,BETAMETHASONE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf19150>,BETAMETHASONE
272,DIHYDROERGOTAMINE_MESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a80>,DIHYDROERGOTAMINE MESYLATE
273,MESORIDAZINE_BESYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45930>,MESORIDAZINE BESYLATE
274,ARIPIPRAZOLE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf459a0>,ARIPIPRAZOLE
275,PROCHLORPERAZINE_EDISYLATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf45a10>,PROCHLORPERAZINE EDISYLATE

In [262]:
import numpy as np

In [263]:
frame["full_smiles"] = np.nan

In [264]:
for i, row in frame.iterrows():
    comp = pcp.get_compounds(frame["ID_pubchem"][i], 'name')
    for c in comp:
        frame["full_smiles"][i] = c.isomeric_smiles

/tmp/ipykernel_540/2065265696.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame["full_smiles"][i] = c.isomeric_smiles
/tmp/ipykernel_540/2065265696.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'CCCC1O[C@@H]2C[C@H]3[C@@H]4CCC5=CC(=O)C=C[C@@]5([C@H]4[C@H](C[C@@]3([C@@]2(O1)C(=O)CO)C)O)C' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  frame["full_smiles"][i] = c.isomeric_smiles

In [267]:
for i, row in frame.iterrows():
    print(frame["ID_pubchem"][i])
    print(frame["full_smiles"][i])

BUDESONIDE
CCCC1O[C@@H]2C[C@H]3[C@@H]4CCC5=CC(=O)C=C[C@@]5([C@H]4[C@H](C[C@@]3([C@@]2(O1)C(=O)CO)C)O)C
BUPROPION
CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C
BURAMATE
C1=CC=C(C=C1)CNC(=O)OCCO
BUSPIRONE
C1CCC2(C1)CC(=O)N(C(=O)C2)CCCCN3CCN(CC3)C4=NC=CC=N4
ABACAVIR SULFATE
C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)C4C[C@@H](C=C4)CO.C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)C4C[C@@H](C=C4)CO.OS(=O)(=O)O
ACEBUTOLOL
CCCC(=O)NC1=CC(=C(C=C1)OCC(CNC(C)C)O)C(=O)C
ACECAINIDE
CCN(CC)CCNC(=O)C1=CC=C(C=C1)NC(=O)C
ALFUZOSIN
CN(CCCNC(=O)C1CCCO1)C2=NC3=CC(=C(C=C3C(=N2)N)OC)OC
ALMOTRIPTAN
CN(C)CCC1=CNC2=C1C=C(C=C2)CS(=O)(=O)N3CCCC3
ALPRENOLOL
CC(C)NCC(COC1=CC=CC=C1CC=C)O
AMANTADINE
C1C2CC3CC1CC(C2)(C3)N
AMINOGLUTETHIMIDE
CCC1(CCC(=O)NC1=O)C2=CC=C(C=C2)N
AMISULPRIDE
CCN1CCCC1CNC(=O)C2=CC(=C(C=C2OC)N)S(=O)(=O)CC
ANAGRELIDE
C1C2=C(C=CC(=C2Cl)Cl)N=C3N1CC(=O)N3
ANASTROZOLE
CC(C)(C#N)C1=CC(=CC(=C1)CN2C=NC=N2)C(C)(C)C#N
ANTAZOLINE PHOSPHATE
C1CN=C(N1)CN(CC2=CC=CC=C2)C3=CC=CC=C3.OP(=O)(O)O
APOMORPHINE
CN1CCC2=C3[C@H]1CC4=C(C3=CC=C2)C(=C(C=C4)O)O
ARTEMISININ
C[C@@H]1CC[C@H]2[C@H](C(=O)O[C@H]3[C@@]24[C@H]1CC[C@](O3)(OO4)C)C
ATENOLOL
CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O
ATORVASTATIN CALCIUM
CC(C)C1=C(C(=C(N1CC[C@H](C[C@H](CC(=O)[O-])O)O)C2=CC=C(C=C2)F)C3=CC=CC=C3)C(=O)NC4=CC=CC=C4.CC(C)C1=C(C(=C(N1CC[C@H](C[C@H](CC(=O)[O-])O)O)C2=CC=C(C=C2)F)C3=CC=CC=C3)C(=O)NC4=CC=CC=C4.O.O.O.[Ca+2]
AZATADINE MALEATE
CN1CCC(=C2C3=CC=CC=C3CCC4=C2N=CC=C4)CC1.C(=C\C(=O)O)\C(=O)O
BAMBUTEROL
CC(C)(C)NCC(C1=CC(=CC(=C1)OC(=O)N(C)C)OC(=O)N(C)C)O
BENAZEPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@H]2CCC3=CC=CC=C3N(C2=O)CC(=O)O
BENZBROMARONE
CCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC(=C(C(=C3)Br)O)Br
BENZTHIAZIDE
C1=CC=C(C=C1)CSCC2=NS(=O)(=O)C3=CC(=C(C=C3N2)Cl)S(=O)(=O)N
BETAMETHASONE ACETATE
C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)COC(=O)C)O)C)O)F)C
BETAMETHASONE VALERATE
CCCCC(=O)O[C@@]1([C@H](C[C@@H]2[C@@]1(C[C@@H]([C@]3([C@H]2CCC4=CC(=O)C=C[C@@]43C)F)O)C)C)C(=O)CO
BETAXALOL
nan
BEZAFIBRATE
CC(C)(C(=O)O)OC1=CC=C(C=C1)CCNC(=O)C2=CC=C(C=C2)Cl
BICALUTAMIDE
CC(CS(=O)(=O)C1=CC=C(C=C1)F)(C(=O)NC2=CC(=C(C=C2)C#N)C(F)(F)F)O
BIPERIDEN
C1CCN(CC1)CCC(C2CC3CC2C=C3)(C4=CC=CC=C4)O
BISACODYL
CC(=O)OC1=CC=C(C=C1)C(C2=CC=C(C=C2)OC(=O)C)C3=CC=CC=N3
BISOPROLOL FUMARATE
CC(C)NCC(COC1=CC=C(C=C1)COCCOC(C)C)O.CC(C)NCC(COC1=CC=C(C=C1)COCCOC(C)C)O
BROMOCRIPTINE MESYLATE
CC(C)C[C@H]1C(=O)N2CCC[C@H]2[C@]3(N1C(=O)[C@](O3)(C(C)C)NC(=O)[C@H]4CN([C@@H]5CC6=C(NC7=CC=CC(=C67)C5=C4)Br)C)O.CS(=O)(=O)O
BUDESONIDE
CCCC1O[C@@H]2C[C@H]3[C@@H]4CCC5=CC(=O)C=C[C@@]5([C@H]4[C@H](C[C@@]3([C@@]2(O1)C(=O)CO)C)O)C
BUPROPION
CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C
BURAMATE
C1=CC=C(C=C1)CNC(=O)OCCO
BUSPIRONE
C1CCC2(C1)CC(=O)N(C(=O)C2)CCCCN3CCN(CC3)C4=NC=CC=N4
CAMYLOFINE
CCN(CC)CCNC(C1=CC=CC=C1)C(=O)OCCC(C)C
CAPECITABINE
CCCCCOC(=O)NC1=NC(=O)N(C=C1F)[C@H]2[C@@H]([C@@H]([C@H](O2)C)O)O
CARBETAPENTANE CITRATE
CCN(CC)CCOCCOC(=O)C1(CCCC1)C2=CC=CC=C2.C(C(=O)O)C(CC(=O)O)(C(=O)O)O
CARBINOXAMINE MALEATE
CN(C)CCOC(C1=CC=C(C=C1)Cl)C2=CC=CC=N2.C(=C\C(=O)O)\C(=O)O
CARISOPRODOL
CCCC(C)(COC(=O)N)COC(=O)NC(C)C
CARVEDILOL
COC1=CC=CC=C1OCCNCC(COC2=CC=CC3=C2C4=CC=CC=C4N3)O
CELECOXIB
CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F
CETIRIZINE
C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl
CHLORMEZANONE
CN1C(S(=O)(=O)CCC1=O)C2=CC=C(C=C2)Cl
CIMETIDINE
CC1=C(N=CN1)CSCCNC(=NC)NC#N
CITALOPRAM HYDROBROMIDE
CN(C)CCCC1(C2=C(CO1)C=C(C=C2)C#N)C3=CC=C(C=C3)F.Br
CLEMASTINE FUMARATE
C[C@@](C1=CC=CC=C1)(C2=CC=C(C=C2)Cl)OCC[C@H]3CCCN3C.C(=C/C(=O)O)\C(=O)O
CLEMIZOLE
C1CCN(C1)CC2=NC3=CC=CC=C3N2CC4=CC=C(C=C4)Cl
CLENBUTEROL
CC(C)(C)NCC(C1=CC(=C(C(=C1)Cl)N)Cl)O
CLIDINIUM BROMIDE
C[N+]12CCC(CC1)C(C2)OC(=O)C(C3=CC=CC=C3)(C4=CC=CC=C4)O.[Br-]
CLONIDINE
C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl
CLOPIDOGREL SULFATE
[H+].COC(=O)[C@H](C1=CC=CC=C1Cl)N2CCC3=C(C2)C=CS3.OS(=O)(=O)[O-]
CLOZAPINE
CN1CCN(CC1)C2=NC3=C(C=CC(=C3)Cl)NC4=CC=CC=C42
COLCHICINE
CC(=O)N[C@H]1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC)OC)OC)OC
CYCLOBENZAPRINE
CN(C)CCC=C1C2=CC=CC=C2C=CC3=CC=CC=C31
CYCLOPHOSPHAMIDE
C1CNP(=O)(OC1)N(CCCl)CCCl
CYPROTERONE ACETATE
CC(=O)[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2C=C(C4=CC(=O)[C@@H]5C[C@@H]5[C@]34C)Cl)C)OC(=O)C
DABIGATRAN ETEXILATE MESYLATE
CCCCCCOC(=O)/N=C(\C1=CC=C(C=C1)NCC2=NC3=C(N2C)C=CC(=C3)C(=O)N(CCC(=O)OCC)C4=CC=CC=N4)/N.CS(=O)(=O)O
DANAZOL
C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=CC5=C(C[C@]34C)C=NO5
DARIFENACIN HYDROBROMIDE
C1CN(C[C@@H]1C(C2=CC=CC=C2)(C3=CC=CC=C3)C(=O)N)CCC4=CC5=C(C=C4)OCC5.Br
DASATINIB
CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(=N3)C)N4CCN(CC4)CCO
DEFLAZACORT
CC1=N[C@@]2([C@H](O1)C[C@@H]3[C@@]2(C[C@@H]([C@H]4[C@H]3CCC5=CC(=O)C=C[C@]45C)O)C)C(=O)COC(=O)C
DESVENLAFAXINE SUCCINATE
CN(C)CC(C1=CC=C(C=C1)O)C2(CCCCC2)O.C(CC(=O)O)C(=O)O
DEXAMETHASONE
C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)CO)O)C)O)F)C
DEXTROMETHORPHAN HYDROBROMIDE
CN1CC[C@@]23CCCC[C@@H]2[C@@H]1CC4=C3C=C(C=C4)OC.O.Br
DIACETAMATE
CC(=O)NC1=CC=C(C=C1)OC(=O)C
DICYCLOMINE
CCN(CC)CCOC(=O)C1(CCCCC1)C2CCCCC2
DIFLORASONE DIACETATE
C[C@H]1C[C@H]2[C@@H]3C[C@@H](C4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)COC(=O)C)OC(=O)C)C)O)F)C)F
DILTIAZEM
CC(=O)O[C@@H]1[C@@H](SC2=CC=CC=C2N(C1=O)CCN(C)C)C3=CC=C(C=C3)OC
DIPERODON
C1CCN(CC1)CC(COC(=O)NC2=CC=CC=C2)OC(=O)NC3=CC=CC=C3
DIPHENYLPYRALINE
CN1CCC(CC1)OC(C2=CC=CC=C2)C3=CC=CC=C3
DIPYRIDAMOLE
C1CCN(CC1)C2=NC(=NC3=C2N=C(N=C3N4CCCCC4)N(CCO)CCO)N(CCO)CCO
DISOPYRAMIDE PHOSPHATE
CC(C)N(CCC(C1=CC=CC=C1)(C2=CC=CC=N2)C(=O)N)C(C)C.OP(=O)(O)O
DOMPERIDONE
C1CN(CCC1N2C3=C(C=C(C=C3)Cl)NC2=O)CCCN4C5=CC=CC=C5NC4=O
DOXAZOSIN MESYLATE
COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4COC5=CC=CC=C5O4)N)OC.CS(=O)(=O)O
DOXEPIN
CN(C)CCC=C1C2=CC=CC=C2COC3=CC=CC=C31
DOXYLAMINE SUCCINATE
CC(C1=CC=CC=C1)(C2=CC=CC=N2)OCCN(C)C.C(CC(=O)O)C(=O)O
DROSPIRENONE
C[C@]12CCC(=O)C=C1[C@@H]3C[C@@H]3[C@@H]4[C@@H]2CC[C@]5([C@H]4[C@@H]6C[C@@H]6[C@@]57CCC(=O)O7)C
DULOXETINE
CNCC[C@@H](C1=CC=CS1)OC2=CC=CC3=CC=CC=C32
ELETRIPTAN HYDROBROMIDE
CN1CCC[C@@H]1CC2=CNC3=C2C=C(C=C3)CCS(=O)(=O)C4=CC=CC=C4.Br
ENALAPRIL MALEATE
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2CCC[C@H]2C(=O)O.C(=C\C(=O)O)\C(=O)O
ENTACAPONE
CCN(CC)C(=O)/C(=C/C1=CC(=C(C(=C1)O)O)[N+](=O)[O-])/C#N
ERGONOVINE MALEATE
C[C@@H](CO)NC(=O)[C@H]1CN([C@@H]2CC3=CNC4=CC=CC(=C34)C2=C1)C.C(=C\C(=O)O)\C(=O)O
ERGOTAMINE TARTRATE
C[C@@]1(C(=O)N2[C@H](C(=O)N3CCC[C@H]3[C@@]2(O1)O)CC4=CC=CC=C4)NC(=O)[C@H]5CN([C@@H]6CC7=CNC8=CC=CC(=C78)C6=C5)C.C[C@@]1(C(=O)N2[C@H](C(=O)N3CCC[C@H]3[C@@]2(O1)O)CC4=CC=CC=C4)NC(=O)[C@H]5CN([C@@H]6CC7=CNC8=CC=CC(=C78)C6=C5)C.C(C(C(=O)O)O)(C(=O)O)O
ESZOPICLONE
CN1CCN(CC1)C(=O)O[C@H]2C3=NC=CN=C3C(=O)N2C4=NC=C(C=C4)Cl
ETHOPROPAZINE
CCN(CC)C(C)CN1C2=CC=CC=C2SC3=CC=CC=C31
ETHOXZOLAMIDE
CCOC1=CC2=C(C=C1)N=C(S2)S(=O)(=O)N
ETHYNODIOL DIACETATE
CC(=O)O[C@H]1CC[C@@H]2[C@H]3CC[C@]4([C@H]([C@@H]3CCC2=C1)CC[C@]4(C#C)OC(=O)C)C
ETODOLAC
CCC1=C2C(=CC=C1)C3=C(N2)C(OCC3)(CC)CC(=O)O
EZETIMIBE
C1=CC(=CC=C1[C@@H]2[C@H](C(=O)N2C3=CC=C(C=C3)F)CC[C@@H](C4=CC=C(C=C4)F)O)O
FAMCICLOVIR
CC(=O)OCC(CCN1C=NC2=CN=C(N=C21)N)COC(=O)C
FAMPROFAZONE
CC(C)C1=C(N(N(C1=O)C2=CC=CC=C2)C)CN(C)C(C)CC3=CC=CC=C3
FEBUXOSTAT
CC1=C(SC(=N1)C2=CC(=C(C=C2)OCC(C)C)C#N)C(=O)O
FENOFIBRATE
CC(C)OC(=O)C(C)(C)OC1=CC=C(C=C1)C(=O)C2=CC=C(C=C2)Cl
FENSPIRIDE
C1CN(CCC12CNC(=O)O2)CCC3=CC=CC=C3
FEXOFENADINE
CC(C)(C1=CC=C(C=C1)C(CCCN2CCC(CC2)C(C3=CC=CC=C3)(C4=CC=CC=C4)O)O)C(=O)O
FINASTERIDE
C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2C(=O)NC(C)(C)C)CC[C@@H]4[C@@]3(C=CC(=O)N4)C
FLUCONAZOLE
C1=CC(=C(C=C1F)F)C(CN2C=NC=N2)(CN3C=NC=N3)O
FLUOXETINE
CNCCC(C1=CC=CC=C1)OC2=CC=C(C=C2)C(F)(F)F
FLUPHENAZINE
C1CN(CCN1CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)C(F)(F)F)CCO
FLUVOXAMINE MALEATE
COCCCC/C(=N/OCCN)/C1=CC=C(C=C1)C(F)(F)F.C(=CC(=O)O)C(=O)O
GALANTAMINE
CN1CC[C@@]23C=C[C@@H](C[C@@H]2OC4=C(C=CC(=C34)C1)OC)O
GLICLAZIDE
CC1=CC=C(C=C1)S(=O)(=O)NC(=O)NN2CC3CCCC3C2
GLIPIZIDE
CC1=CN=C(C=N1)C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)NC(=O)NC3CCCCC3
GRISEOFULVIN
C[C@@H]1CC(=O)C=C([C@]12C(=O)C3=C(O2)C(=C(C=C3OC)OC)Cl)OC
GUANFACINE
C1=CC(=C(C(=C1)Cl)CC(=O)N=C(N)N)Cl
HALOPERIDOL
C1CN(CCC1(C2=CC=C(C=C2)Cl)O)CCCC(=O)C3=CC=C(C=C3)F
HYOSCYAMINE
CN1[C@H]2CCC1CC(C2)OC(=O)[C@H](CO)C3=CC=CC=C3
IDEBENONE
CC1=C(C(=O)C(=C(C1=O)OC)OC)CCCCCCCCCCO
IMATINIB
CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5
INDAPAMIDE
CC1CC2=CC=CC=C2N1NC(=O)C3=CC(=C(C=C3)Cl)S(=O)(=O)N
INDOMETHACIN
CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)O
IRBESARTAN
CCCCC1=NC2(CCCC2)C(=O)N1CC3=CC=C(C=C3)C4=CC=CC=C4C5=NNN=N5
IRSOGLADINE MALEATE
C1=CC(=C(C=C1Cl)C2=NC(=NC(=N2)N)N)Cl.C(=C\C(=O)O)\C(=O)O
ISRADIPINE
CC1=C(C(C(=C(N1)C)C(=O)OC(C)C)C2=CC=CC3=NON=C32)C(=O)OC
ITRACONAZOLE
CCC(C)N1C(=O)N(C=N1)C2=CC=C(C=C2)N3CCN(CC3)C4=CC=C(C=C4)OCC5CO[C@](O5)(CN6C=NC=N6)C7=C(C=C(C=C7)Cl)Cl
KETOROLAC TROMETHAMINE
C1CN2C(=CC=C2C(=O)C3=CC=CC=C3)C1C(=O)O.C(C(CO)(CO)N)O
KETOTIFEN FUMARATE
CN1CCC(=C2C3=C(C(=O)CC4=CC=CC=C42)SC=C3)CC1.C(=C/C(=O)O)\C(=O)O
LABETALOL
CC(CCC1=CC=CC=C1)NCC(C2=CC(=C(C=C2)O)C(=O)N)O
LAMOTRIGINE
C1=CC(=C(C(=C1)Cl)Cl)C2=C(N=C(N=N2)N)N
LETROZOLE
C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3
LEVAMISOLE
C1CSC2=N[C@H](CN21)C3=CC=CC=C3
LEVONORGESTREL
CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=CC(=O)CC[C@H]34
LINAGLIPTIN
CC#CCN1C2=C(N=C1N3CCC[C@H](C3)N)N(C(=O)N(C2=O)CC4=NC5=CC=CC=C5C(=N4)C)C
LOFEXIDINE
CC(C1=NCCN1)OC2=C(C=CC=C2Cl)Cl
LOPERAMIDE
CN(C)C(=O)C(CCN1CCC(CC1)(C2=CC=C(C=C2)Cl)O)(C3=CC=CC=C3)C4=CC=CC=C4
LOSARTAN
CCCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NNN=N4)CO)Cl
LOVASTATIN
CC[C@H](C)C(=O)O[C@H]1C[C@H](C=C2[C@H]1[C@H]([C@H](C=C2)C)CC[C@@H]3C[C@H](CC(=O)O3)O)C
LOXAPINE SUCCINATE
CN1CCN(CC1)C2=NC3=CC=CC=C3OC4=C2C=C(C=C4)Cl.C(CC(=O)O)C(=O)O
MEBENDAZOLE
COC(=O)NC1=NC2=C(N1)C=C(C=C2)C(=O)C3=CC=CC=C3
MEBHYDROLIN NAPHTHALENESULFONATE
CN1CCC2=C(C1)C3=CC=CC=C3N2CC4=CC=CC=C4.C1=CC2=C(C=CC=C2S(=O)(=O)O)C(=C1)S(=O)(=O)O
MEFLOQUINE
C1CCNC(C1)[C@H](C2=CC(=NC3=C2C=CC=C3C(F)(F)F)C(F)(F)F)O
MEGESTROL ACETATE
CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC[C@@]3(C(=O)C)OC(=O)C)C)[C@@]4(C1=CC(=O)CC4)C
MELPHALAN
C1=CC(=CC=C1C[C@@H](C(=O)O)N)N(CCCl)CCCl
MEMANTINE
CC12CC3CC(C1)(CC(C3)(C2)N)C
METAXALONE
CC1=CC(=CC(=C1)OCC2CNC(=O)O2)C
METHOCARBAMOL
COC1=CC=CC=C1OCC(COC(=O)N)O
METHOXSALEN
COC1=C2C(=CC3=C1OC=C3)C=CC(=O)O2
METHSUXIMIDE
CC1(CC(=O)N(C1=O)C)C2=CC=CC=C2
METHYLPHENIDATE
COC(=O)C(C1CCCCN1)C2=CC=CC=C2
METHYSERGIDE MALEATE
CC[C@@H](CO)NC(=O)[C@H]1CN([C@@H]2CC3=CN(C4=CC=CC(=C34)C2=C1)C)C.C(=C\C(=O)O)\C(=O)O
METICRANE
CC1=CC2=C(C=C1S(=O)(=O)N)S(=O)(=O)CCC2
METITEPINE MALEATE
CN1CCN(CC1)C2CC3=CC=CC=C3SC4=C2C=C(C=C4)SC.C(=C\C(=O)O)\C(=O)O
METOCLOPRAMIDE
CCN(CC)CCNC(=O)C1=CC(=C(C=C1OC)N)Cl
METOLAZONE
CC1NC2=CC(=C(C=C2C(=O)N1C3=CC=CC=C3C)S(=O)(=O)N)Cl
METOPROLOL TARTRATE
CC(C)NCC(COC1=CC=C(C=C1)CCOC)O.CC(C)NCC(COC1=CC=C(C=C1)CCOC)O.[C@@H](C(C(=O)O)O)(C(=O)O)O
MEVASTATIN
CC[C@H](C)C(=O)O[C@H]1CCC=C2[C@H]1[C@H]([C@H](C=C2)C)CC[C@@H]3C[C@H](CC(=O)O3)O
MIANSERIN
CN1CCN2C(C1)C3=CC=CC=C3CC4=CC=CC=C42
MIFEPRISTONE
CC#C[C@@]1(CC[C@@H]2[C@@]1(C[C@@H](C3=C4CCC(=O)C=C4CC[C@@H]23)C5=CC=C(C=C5)N(C)C)C)O
MILNACIPRAN
CCN(CC)C(=O)[C@@]1(C[C@@H]1CN)C2=CC=CC=C2
MYCOPHENOLATE MOFETIL
CC1=C2COC(=O)C2=C(C(=C1OC)C/C=C(\C)/CCC(=O)OCCN3CCOCC3)O
NADOLOL
CC(C)(C)NCC(COC1=CC=CC2=C1C[C@@H]([C@@H](C2)O)O)O
NAFRONYL OXALATE
CCN(CC)CCOC(=O)C(CC1CCCO1)CC2=CC=CC3=CC=CC=C32.C(=O)(C(=O)O)O
NAFTOPIDIL
COC1=CC=CC=C1N2CCN(CC2)CC(COC3=CC=CC4=CC=CC=C43)O
NALOXONE
C=CCN1CC[C@]23[C@@H]4C(=O)CC[C@]2([C@H]1CC5=C3C(=C(C=C5)O)O4)O
NAPROXEN
C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O
NATEGLINIDE
CC(C)C1CCC(CC1)C(=O)N[C@H](CC2=CC=CC=C2)C(=O)O
NEFAZODONE
CCC1=NN(C(=O)N1CCOC2=CC=CC=C2)CCCN3CCN(CC3)C4=CC(=CC=C4)Cl
NEFOPAM
CN1CCOC(C2=CC=CC=C2C1)C3=CC=CC=C3
NEOSTIGMINE BROMIDE
CN(C)C(=O)OC1=CC=CC(=C1)[N+](C)(C)C.[Br-]
NEVIRAPINE
CC1=C2C(=NC=C1)N(C3=C(C=CC=N3)C(=O)N2)C4CC4
NICERGOLINE
CN1C[C@@H](C[C@]2([C@H]1CC3=CN(C4=CC=CC2=C34)C)OC)COC(=O)C5=CC(=CN=C5)Br
NITRENDIPINE
CCOC(=O)C1=C(NC(=C(C1C2=CC(=CC=C2)[N+](=O)[O-])C(=O)OC)C)C
NIZATIDINE
CN/C(=C\[N+](=O)[O-])/NCCSCC1=CSC(=N1)CN(C)C
NORETHINDRONE ACETATE
CC(=O)O[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4=CC(=O)CC[C@H]34)C)C#C
NORGESTIMATE
CC[C@@]12CC[C@@H]3[C@@H]([C@H]1CC[C@@]2(C#C)OC(=O)C)CCC4=C/C(=N/O)/CC[C@@H]34
NOSCAPINE
CN1CCC2=CC3=C(C(=C2[C@@H]1[C@@H]4C5=C(C(=C(C=C5)OC)OC)C(=O)O4)OC)OCO3
OLANZAPINE
CC1=CC2=C(S1)NC3=CC=CC=C3N=C2N4CCN(CC4)C
OLMESARTAN MEDOXOMIL
CCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NNN=N4)C(=O)OCC5=C(OC(=O)O5)C)C(C)(C)O
OMEPRAZOLE
CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC
ORPHENADRINE CITRATE
CC1=CC=CC=C1C(C2=CC=CC=C2)OCCN(C)C.C(C(=O)O)C(CC(=O)O)(C(=O)O)O
OXAPROZIN
C1=CC=C(C=C1)C2=C(OC(=N2)CCC(=O)O)C3=CC=CC=C3
OXCARBAZEPINE
C1C2=CC=CC=C2N(C3=CC=CC=C3C1=O)C(=O)N
OXETHAZAINE
CC(C)(CC1=CC=CC=C1)N(C)C(=O)CN(CCO)CC(=O)N(C)C(C)(C)CC2=CC=CC=C2
OXYBUTYNIN CHLORIDE
CCN(CC)CC#CCOC(=O)C(C1CCCCC1)(C2=CC=CC=C2)O.Cl
PACLITAXEL
CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@H]3[C@@H]([C@@](C2(C)C)(C[C@@H]1OC(=O)[C@@H]([C@H](C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C
PALIPERIDONE
CC1=C(C(=O)N2CCCC(C2=N1)O)CCN3CCC(CC3)C4=NOC5=C4C=CC(=C5)F
PANTOPRAZOLE
COC1=C(C(=NC=C1)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC(F)F)OC
PAPAVERINE
COC1=C(C=C(C=C1)CC2=NC=CC3=CC(=C(C=C32)OC)OC)OC
PAROXETINE
C1CNC[C@H]([C@@H]1C2=CC=C(C=C2)F)COC3=CC4=C(C=C3)OCO4
PENBUTOLOL SULFATE
CC(C)(C)NC[C@@H](COC1=CC=CC=C1C2CCCC2)O.CC(C)(C)NC[C@@H](COC1=CC=CC=C1C2CCCC2)O.OS(=O)(=O)O
PENTOXIFYLLINE
CC(=O)CCCCN1C(=O)C2=C(N=CN2C)N(C1=O)C
PERGOLIDE MESYLATE
CCCN1C[C@@H](C[C@H]2[C@H]1CC3=CNC4=CC=CC2=C34)CSC.CS(=O)(=O)O
PERICYAZINE
C1CN(CCC1O)CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)C#N
PERINDOPRIL ERBUMINE
CCC[C@@H](C(=O)OCC)N[C@@H](C)C(=O)N1[C@H]2CCCC[C@H]2C[C@H]1C(=O)O.CC(C)(C)N
PHENACETIN
CCOC1=CC=C(C=C1)NC(=O)C
PHENAZOPYRIDINE
C1=CC=C(C=C1)N=NC2=C(N=C(C=C2)N)N
PHENYTOIN SODIUM
C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3.[Na+]
PIDOTIMOD
C1CC(=O)N[C@@H]1C(=O)N2CSC[C@H]2C(=O)O
PIMOZIDE
C1CN(CCC1N2C3=CC=CC=C3NC2=O)CCCC(C4=CC=C(C=C4)F)C5=CC=C(C=C5)F
PITAVASTATIN CALCIUM
C1CC1C2=NC3=CC=CC=C3C(=C2/C=C/[C@H](C[C@H](CC(=O)O)O)O)C4=CC=C(C=C4)F.[Ca]
PRANOPROFEN
CC(C1=CC2=C(C=C1)OC3=C(C2)C=CC=N3)C(=O)O
PRAZOSIN
COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4=CC=CO4)N)OC
PREDNISONE
C[C@]12CC(=O)[C@H]3[C@H]([C@@H]1CC[C@@]2(C(=O)CO)O)CCC4=CC(=O)C=C[C@]34C
PRIDINOL METHANESULFONATE
CS(=O)(=O)O.C1CCN(CC1)CCC(C2=CC=CC=C2)(C3=CC=CC=C3)O
PRIMAQUINE PHOSPHATE
CC(CCCN)NC1=C2C(=CC(=C1)OC)C=CC=N2.OP(=O)(O)O.OP(=O)(O)O
PROCARBAZINE
CC(C)NC(=O)C1=CC=C(C=C1)CNNC
PROMETHAZINE
CC(CN1C2=CC=CC=C2SC3=CC=CC=C31)N(C)C
PYRIMETHAMINE
CCC1=C(C(=NC(=N1)N)N)C2=CC=C(C=C2)Cl
QUETIAPINE
C1CN(CCN1CCOCCO)C2=NC3=CC=CC=C3SC4=CC=CC=C42
QUINAPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2CC3=CC=CC=C3C[C@H]2C(=O)O
QUININE SULFATE
[H+].[H+].COC1=CC2=C(C=CN=C2C=C1)[C@H]([C@@H]3C[C@@H]4CCN3C[C@@H]4C=C)O.COC1=CC2=C(C=CN=C2C=C1)[C@H]([C@@H]3C[C@@H]4CCN3C[C@@H]4C=C)O.[O-]S(=O)(=O)[O-]
RACECADOTRIL
CC(=O)SCC(CC1=CC=CC=C1)C(=O)NCC(=O)OCC2=CC=CC=C2
RAMELTEON
CCC(=O)NCC[C@@H]1CCC2=C1C3=C(C=C2)OCC3
RAMIPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2[C@H]3CCC[C@H]3C[C@H]2C(=O)O
RANITIDINE
CN/C(=C\[N+](=O)[O-])/NCCSCC1=CC=C(O1)CN(C)C
RANOLAZINE
CC1=C(C(=CC=C1)C)NC(=O)CN2CCN(CC2)CC(COC3=CC=CC=C3OC)O
REBAMIPIDE
C1=CC=C2C(=C1)C(=CC(=O)N2)CC(C(=O)O)NC(=O)C3=CC=C(C=C3)Cl
REPAGLINIDE
CCOC1=C(C=CC(=C1)CC(=O)N[C@@H](CC(C)C)C2=CC=CC=C2N3CCCCC3)C(=O)O
RESERPINE
CO[C@H]1[C@@H](C[C@@H]2CN3CCC4=C([C@H]3C[C@@H]2[C@@H]1C(=O)OC)NC5=C4C=CC(=C5)OC)OC(=O)C6=CC(=C(C(=C6)OC)OC)OC
RILUZOLE
C1=CC2=C(C=C1OC(F)(F)F)SC(=N2)N
RIMANTADINE
CC(C12CC3CC(C1)CC(C3)C2)N
RISPERIDONE
CC1=C(C(=O)N2CCCCC2=N1)CCN3CCC(CC3)C4=NOC5=C4C=CC(=C5)F
RITONAVIR
CC(C)C1=NC(=CS1)CN(C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CC2=CC=CC=C2)C[C@@H]([C@H](CC3=CC=CC=C3)NC(=O)OCC4=CN=CS4)O
RIVASTIGMINE TARTRATE
CCN(C)C(=O)OC1=CC=CC(=C1)C(C)N(C)C.[C@@H]([C@H](C(=O)O)O)(C(=O)O)O
RIZATRIPTAN BENZOATE
CN(C)CCC1=CNC2=C1C=C(C=C2)CN3C=NC=N3.C1=CC=C(C=C1)C(=O)O
ROPINIROLE
CCCN(CCC)CCC1=C2CC(=O)NC2=CC=C1
ROSIGLITAZONE MALEATE
CN(CCOC1=CC=C(C=C1)CC2C(=O)NC(=O)S2)C3=CC=CC=N3.C(=C\C(=O)O)\C(=O)O
ROSUVASTATIN CALCIUM
CC(C)C1=NC(=NC(=C1/C=C/[C@H](C[C@H](CC(=O)O)O)O)C2=CC=C(C=C2)F)N(C)S(=O)(=O)C.[Ca+2]
ROXATIDINE ACETATE
CC(=O)OCC(=O)NCCCOC1=CC=CC(=C1)CN2CCCCC2
SERTRALINE
CN[C@H]1CC[C@H](C2=CC=CC=C12)C3=CC(=C(C=C3)Cl)Cl
SILDENAFIL CITRATE
CCCC1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C.C(C(=O)O)C(CC(=O)O)(C(=O)O)O
SOLIFENACIN SUCCINATE
C1CN2CCC1[C@H](C2)OC(=O)N3CCC4=CC=CC=C4[C@@H]3C5=CC=CC=C5.C(CC(=O)O)C(=O)O
SOTALOL
CC(C)NCC(C1=CC=C(C=C1)NS(=O)(=O)C)O
SPIPERONE
C1CN(CCC12C(=O)NCN2C3=CC=CC=C3)CCCC(=O)C4=CC=C(C=C4)F
SULFASALAZINE
C1=CC=NC(=C1)NS(=O)(=O)C2=CC=C(C=C2)N=NC3=CC(=C(C=C3)O)C(=O)O
SULFINPYRAZONE
C1=CC=C(C=C1)N2C(=O)C(C(=O)N2C3=CC=CC=C3)CCS(=O)C4=CC=CC=C4
SULINDAC
CC\1=C(C2=C(/C1=C\C3=CC=C(C=C3)S(=O)C)C=CC(=C2)F)CC(=O)O
SULPIRIDE
CCN1CCCC1CNC(=O)C2=C(C=CC(=C2)S(=O)(=O)N)OC
SUMATRIPTAN SUCCINATE
CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C.C(CC(=O)O)C(=O)O
TACRINE
C1CCC2=NC3=CC=CC=C3C(=C2C1)N
TACROLIMUS
C[C@@H]1C[C@@H]([C@@H]2[C@H](C[C@H]([C@@](O2)(C(=O)C(=O)N3CCCC[C@H]3C(=O)O[C@@H]([C@@H]([C@H](CC(=O)[C@@H](/C=C(/C1)\C)CC=C)O)C)/C(=C/[C@@H]4CC[C@H]([C@@H](C4)OC)O)/C)O)C)OC)OC
TADALAFIL
CN1CC(=O)N2[C@@H](C1=O)CC3=C([C@H]2C4=CC5=C(C=C4)OCO5)NC6=CC=CC=C36
TAMSULOSIN HYDRCHLORIDE
nan
TEGASEROD MALEATE
CCCCCN=C(N)N/N=C\C1=CNC2=C1C=C(C=C2)OC.C(=C/C(=O)O)\C(=O)O
TELMISARTAN
CCCC1=NC2=C(N1CC3=CC=C(C=C3)C4=CC=CC=C4C(=O)O)C=C(C=C2C)C5=NC6=CC=CC=C6N5C
TENATOPRAZOLE
CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=CC(=N3)OC
TENOXICAM
CN1C(=C(C2=C(S1(=O)=O)C=CS2)O)C(=O)NC3=CC=CC=N3
TERAZOSIN
COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4CCCO4)N)OC
TERBINAFINE
CC(C)(C)C#C/C=C/CN(C)CC1=CC=CC2=CC=CC=C21
THIABENDAZOLE
C1=CC=C2C(=C1)NC(=N2)C3=CSC=N3
THIOTHIXENE
CN1CCN(CC1)CCC=C2C3=CC=CC=C3SC4=C2C=C(C=C4)S(=O)(=O)N(C)C
TIAPRIDE
CCN(CC)CCNC(=O)C1=C(C=CC(=C1)S(=O)(=O)C)OC
TIMOLOL MALEATE
CC(C)(C)NC[C@@H](COC1=NSN=C1N2CCOCC2)O.C(=C\C(=O)O)\C(=O)O
TINIDAZOLE
CCS(=O)(=O)CCN1C(=NC=C1[N+](=O)[O-])C
TOLAZAMIDE
CC1=CC=C(C=C1)S(=O)(=O)NC(=O)NN2CCCCCC2
TOPOTECAN
CC[C@@]1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5CN(C)C)O)N=C4C3=C2)O
TRANDOLAPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2[C@H]3CCCC[C@@H]3C[C@H]2C(=O)O
TRANILAST
COC1=C(C=C(C=C1)/C=C/C(=O)NC2=CC=CC=C2C(=O)O)OC
TRAZODONE
C1CN(CCN1CCCN2C(=O)N3C=CC=CC3=N2)C4=CC(=CC=C4)Cl
TRIHEXYPHENIDYL
C1CCC(CC1)C(CCN2CCCCC2)(C3=CC=CC=C3)O
TRIMEBUTINE MALEATE
CCC(COC(=O)C1=CC(=C(C(=C1)OC)OC)OC)(C2=CC=CC=C2)N(C)C.C(=C\C(=O)O)\C(=O)O
TRIMETAZIDINE
COC1=C(C(=C(C=C1)CN2CCNCC2)OC)OC
TRIMETHOBENZAMIDE
CN(C)CCOC1=CC=C(C=C1)CNC(=O)C2=CC(=C(C(=C2)OC)OC)OC
TRIMIPRAMINE MALEATE
CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C.C(=C\C(=O)O)\C(=O)O
TRIPROLIDINE
CC1=CC=C(C=C1)/C(=C\CN2CCCC2)/C3=CC=CC=N3
TROPISETRON
CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C3=CNC4=CC=CC=C43
VALSARTAN
CCCCC(=O)N(CC1=CC=C(C=C1)C2=CC=CC=C2C3=NNN=N3)[C@@H](C(C)C)C(=O)O
VENLAFAXINE
CN(C)CC(C1=CC=C(C=C1)OC)C2(CCCCC2)O
VERAPAMIL
CC(C)C(CCCN(C)CCC1=CC(=C(C=C1)OC)OC)(C#N)C2=CC(=C(C=C2)OC)OC
VILAZODONE
C1CN(CCN1CCCCC2=CNC3=C2C=C(C=C3)C#N)C4=CC5=C(C=C4)OC(=C5)C(=O)N
VINPOCETINE
CC[C@@]12CCCN3[C@@H]1C4=C(CC3)C5=CC=CC=C5N4C(=C2)C(=O)OCC
VORICONAZOLE
C[C@@H](C1=NC=NC=C1F)[C@](CN2C=NC=N2)(C3=C(C=C(C=C3)F)F)O
WARFARIN
CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O
ZALEPLON
CCN(C1=CC=CC(=C1)C2=CC=NC3=C(C=NN23)C#N)C(=O)C
ZIDOVUDINE  AZT
nan
ZIPRASIDONE MESYLATE
CS(=O)(=O)O.C1CN(CCN1CCC2=C(C=C3C(=C2)CC(=O)N3)Cl)C4=NSC5=CC=CC=C54.O.O.O
ZOLPIDEM
CC1=CC=C(C=C1)C2=C(N3C=C(C=CC3=N2)C)CC(=O)N(C)C
BETAMETHASONE
C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)CO)O)C)O)F)C
DIHYDROERGOTAMINE MESYLATE
C[C@@]1(C(=O)N2[C@H](C(=O)N3CCC[C@H]3[C@@]2(O1)O)CC4=CC=CC=C4)NC(=O)[C@@H]5C[C@H]6[C@@H](CC7=CNC8=CC=CC6=C78)N(C5)C.CS(=O)(=O)O
MESORIDAZINE BESYLATE
CN1CCCCC1CCN2C3=CC=CC=C3SC4=C2C=C(C=C4)S(=O)C.C1=CC=C(C=C1)S(=O)(=O)O
ARIPIPRAZOLE
C1CC(=O)NC2=C1C=CC(=C2)OCCCCN3CCN(CC3)C4=C(C(=CC=C4)Cl)Cl
PROCHLORPERAZINE EDISYLATE
CN1CCN(CC1)CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)Cl.C(CS(=O)(=O)O)S(=O)(=O)O

In [270]:
frame[frame["ID_pubchem"] == "ZIDOVUDINE  AZT"]
frame[frame["ID_pubchem"] == "TAMSULOSIN HYDRCHLORIDE"]
#frame[frame["ID_pubchem"] == "BETAXALOL"]

,ID,ROMol,ID_pubchem,full_smiles
236,TAMSULOSIN_HYDRCHLORIDE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf4ad50>,TAMSULOSIN HYDRCHLORIDE,NaN

In [271]:
print(frame["ID_pubchem"][27])
print(frame["ID_pubchem"][268])
print(frame["ID_pubchem"][236])

BETAXALOL
ZIDOVUDINE  AZT
TAMSULOSIN HYDRCHLORIDE

In [272]:
frame["full_smiles"][27] = "CC(C)NCC(COC1=CC=C(C=C1)CCOCC2CC2)O"
frame["full_smiles"][268] = "CC1=CN(C(=O)NC1=O)[C@H]2C[C@@H]([C@H](O2)CO)N=[N+]=[N-]"
frame["full_smiles"][236] = "CCOC1=CC=CC=C1OCCN[C@H](C)CC2=CC(=C(C=C2)OC)S(=O)(=O)N"

In [273]:
 # remove salts or any other ions
frame["SMILES"] = [max(str(i).split("."), key=len) for i in frame["full_smiles"]]

In [274]:
for i, row in frame.iterrows():
    print(frame["ID_pubchem"][i])
    print(frame["SMILES"][i])

BUDESONIDE
CCCC1O[C@@H]2C[C@H]3[C@@H]4CCC5=CC(=O)C=C[C@@]5([C@H]4[C@H](C[C@@]3([C@@]2(O1)C(=O)CO)C)O)C
BUPROPION
CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C
BURAMATE
C1=CC=C(C=C1)CNC(=O)OCCO
BUSPIRONE
C1CCC2(C1)CC(=O)N(C(=O)C2)CCCCN3CCN(CC3)C4=NC=CC=N4
ABACAVIR SULFATE
C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)C4C[C@@H](C=C4)CO
ACEBUTOLOL
CCCC(=O)NC1=CC(=C(C=C1)OCC(CNC(C)C)O)C(=O)C
ACECAINIDE
CCN(CC)CCNC(=O)C1=CC=C(C=C1)NC(=O)C
ALFUZOSIN
CN(CCCNC(=O)C1CCCO1)C2=NC3=CC(=C(C=C3C(=N2)N)OC)OC
ALMOTRIPTAN
CN(C)CCC1=CNC2=C1C=C(C=C2)CS(=O)(=O)N3CCCC3
ALPRENOLOL
CC(C)NCC(COC1=CC=CC=C1CC=C)O
AMANTADINE
C1C2CC3CC1CC(C2)(C3)N
AMINOGLUTETHIMIDE
CCC1(CCC(=O)NC1=O)C2=CC=C(C=C2)N
AMISULPRIDE
CCN1CCCC1CNC(=O)C2=CC(=C(C=C2OC)N)S(=O)(=O)CC
ANAGRELIDE
C1C2=C(C=CC(=C2Cl)Cl)N=C3N1CC(=O)N3
ANASTROZOLE
CC(C)(C#N)C1=CC(=CC(=C1)CN2C=NC=N2)C(C)(C)C#N
ANTAZOLINE PHOSPHATE
C1CN=C(N1)CN(CC2=CC=CC=C2)C3=CC=CC=C3
APOMORPHINE
CN1CCC2=C3[C@H]1CC4=C(C3=CC=C2)C(=C(C=C4)O)O
ARTEMISININ
C[C@@H]1CC[C@H]2[C@H](C(=O)O[C@H]3[C@@]24[C@H]1CC[C@](O3)(OO4)C)C
ATENOLOL
CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O
ATORVASTATIN CALCIUM
CC(C)C1=C(C(=C(N1CC[C@H](C[C@H](CC(=O)[O-])O)O)C2=CC=C(C=C2)F)C3=CC=CC=C3)C(=O)NC4=CC=CC=C4
AZATADINE MALEATE
CN1CCC(=C2C3=CC=CC=C3CCC4=C2N=CC=C4)CC1
BAMBUTEROL
CC(C)(C)NCC(C1=CC(=CC(=C1)OC(=O)N(C)C)OC(=O)N(C)C)O
BENAZEPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@H]2CCC3=CC=CC=C3N(C2=O)CC(=O)O
BENZBROMARONE
CCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC(=C(C(=C3)Br)O)Br
BENZTHIAZIDE
C1=CC=C(C=C1)CSCC2=NS(=O)(=O)C3=CC(=C(C=C3N2)Cl)S(=O)(=O)N
BETAMETHASONE ACETATE
C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)COC(=O)C)O)C)O)F)C
BETAMETHASONE VALERATE
CCCCC(=O)O[C@@]1([C@H](C[C@@H]2[C@@]1(C[C@@H]([C@]3([C@H]2CCC4=CC(=O)C=C[C@@]43C)F)O)C)C)C(=O)CO
BETAXALOL
CC(C)NCC(COC1=CC=C(C=C1)CCOCC2CC2)O
BEZAFIBRATE
CC(C)(C(=O)O)OC1=CC=C(C=C1)CCNC(=O)C2=CC=C(C=C2)Cl
BICALUTAMIDE
CC(CS(=O)(=O)C1=CC=C(C=C1)F)(C(=O)NC2=CC(=C(C=C2)C#N)C(F)(F)F)O
BIPERIDEN
C1CCN(CC1)CCC(C2CC3CC2C=C3)(C4=CC=CC=C4)O
BISACODYL
CC(=O)OC1=CC=C(C=C1)C(C2=CC=C(C=C2)OC(=O)C)C3=CC=CC=N3
BISOPROLOL FUMARATE
CC(C)NCC(COC1=CC=C(C=C1)COCCOC(C)C)O
BROMOCRIPTINE MESYLATE
CC(C)C[C@H]1C(=O)N2CCC[C@H]2[C@]3(N1C(=O)[C@](O3)(C(C)C)NC(=O)[C@H]4CN([C@@H]5CC6=C(NC7=CC=CC(=C67)C5=C4)Br)C)O
BUDESONIDE
CCCC1O[C@@H]2C[C@H]3[C@@H]4CCC5=CC(=O)C=C[C@@]5([C@H]4[C@H](C[C@@]3([C@@]2(O1)C(=O)CO)C)O)C
BUPROPION
CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C
BURAMATE
C1=CC=C(C=C1)CNC(=O)OCCO
BUSPIRONE
C1CCC2(C1)CC(=O)N(C(=O)C2)CCCCN3CCN(CC3)C4=NC=CC=N4
CAMYLOFINE
CCN(CC)CCNC(C1=CC=CC=C1)C(=O)OCCC(C)C
CAPECITABINE
CCCCCOC(=O)NC1=NC(=O)N(C=C1F)[C@H]2[C@@H]([C@@H]([C@H](O2)C)O)O
CARBETAPENTANE CITRATE
CCN(CC)CCOCCOC(=O)C1(CCCC1)C2=CC=CC=C2
CARBINOXAMINE MALEATE
CN(C)CCOC(C1=CC=C(C=C1)Cl)C2=CC=CC=N2
CARISOPRODOL
CCCC(C)(COC(=O)N)COC(=O)NC(C)C
CARVEDILOL
COC1=CC=CC=C1OCCNCC(COC2=CC=CC3=C2C4=CC=CC=C4N3)O
CELECOXIB
CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F
CETIRIZINE
C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl
CHLORMEZANONE
CN1C(S(=O)(=O)CCC1=O)C2=CC=C(C=C2)Cl
CIMETIDINE
CC1=C(N=CN1)CSCCNC(=NC)NC#N
CITALOPRAM HYDROBROMIDE
CN(C)CCCC1(C2=C(CO1)C=C(C=C2)C#N)C3=CC=C(C=C3)F
CLEMASTINE FUMARATE
C[C@@](C1=CC=CC=C1)(C2=CC=C(C=C2)Cl)OCC[C@H]3CCCN3C
CLEMIZOLE
C1CCN(C1)CC2=NC3=CC=CC=C3N2CC4=CC=C(C=C4)Cl
CLENBUTEROL
CC(C)(C)NCC(C1=CC(=C(C(=C1)Cl)N)Cl)O
CLIDINIUM BROMIDE
C[N+]12CCC(CC1)C(C2)OC(=O)C(C3=CC=CC=C3)(C4=CC=CC=C4)O
CLONIDINE
C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl
CLOPIDOGREL SULFATE
COC(=O)[C@H](C1=CC=CC=C1Cl)N2CCC3=C(C2)C=CS3
CLOZAPINE
CN1CCN(CC1)C2=NC3=C(C=CC(=C3)Cl)NC4=CC=CC=C42
COLCHICINE
CC(=O)N[C@H]1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC)OC)OC)OC
CYCLOBENZAPRINE
CN(C)CCC=C1C2=CC=CC=C2C=CC3=CC=CC=C31
CYCLOPHOSPHAMIDE
C1CNP(=O)(OC1)N(CCCl)CCCl
CYPROTERONE ACETATE
CC(=O)[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2C=C(C4=CC(=O)[C@@H]5C[C@@H]5[C@]34C)Cl)C)OC(=O)C
DABIGATRAN ETEXILATE MESYLATE
CCCCCCOC(=O)/N=C(\C1=CC=C(C=C1)NCC2=NC3=C(N2C)C=CC(=C3)C(=O)N(CCC(=O)OCC)C4=CC=CC=N4)/N
DANAZOL
C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=CC5=C(C[C@]34C)C=NO5
DARIFENACIN HYDROBROMIDE
C1CN(C[C@@H]1C(C2=CC=CC=C2)(C3=CC=CC=C3)C(=O)N)CCC4=CC5=C(C=C4)OCC5
DASATINIB
CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(=N3)C)N4CCN(CC4)CCO
DEFLAZACORT
CC1=N[C@@]2([C@H](O1)C[C@@H]3[C@@]2(C[C@@H]([C@H]4[C@H]3CCC5=CC(=O)C=C[C@]45C)O)C)C(=O)COC(=O)C
DESVENLAFAXINE SUCCINATE
CN(C)CC(C1=CC=C(C=C1)O)C2(CCCCC2)O
DEXAMETHASONE
C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)CO)O)C)O)F)C
DEXTROMETHORPHAN HYDROBROMIDE
CN1CC[C@@]23CCCC[C@@H]2[C@@H]1CC4=C3C=C(C=C4)OC
DIACETAMATE
CC(=O)NC1=CC=C(C=C1)OC(=O)C
DICYCLOMINE
CCN(CC)CCOC(=O)C1(CCCCC1)C2CCCCC2
DIFLORASONE DIACETATE
C[C@H]1C[C@H]2[C@@H]3C[C@@H](C4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)COC(=O)C)OC(=O)C)C)O)F)C)F
DILTIAZEM
CC(=O)O[C@@H]1[C@@H](SC2=CC=CC=C2N(C1=O)CCN(C)C)C3=CC=C(C=C3)OC
DIPERODON
C1CCN(CC1)CC(COC(=O)NC2=CC=CC=C2)OC(=O)NC3=CC=CC=C3
DIPHENYLPYRALINE
CN1CCC(CC1)OC(C2=CC=CC=C2)C3=CC=CC=C3
DIPYRIDAMOLE
C1CCN(CC1)C2=NC(=NC3=C2N=C(N=C3N4CCCCC4)N(CCO)CCO)N(CCO)CCO
DISOPYRAMIDE PHOSPHATE
CC(C)N(CCC(C1=CC=CC=C1)(C2=CC=CC=N2)C(=O)N)C(C)C
DOMPERIDONE
C1CN(CCC1N2C3=C(C=C(C=C3)Cl)NC2=O)CCCN4C5=CC=CC=C5NC4=O
DOXAZOSIN MESYLATE
COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4COC5=CC=CC=C5O4)N)OC
DOXEPIN
CN(C)CCC=C1C2=CC=CC=C2COC3=CC=CC=C31
DOXYLAMINE SUCCINATE
CC(C1=CC=CC=C1)(C2=CC=CC=N2)OCCN(C)C
DROSPIRENONE
C[C@]12CCC(=O)C=C1[C@@H]3C[C@@H]3[C@@H]4[C@@H]2CC[C@]5([C@H]4[C@@H]6C[C@@H]6[C@@]57CCC(=O)O7)C
DULOXETINE
CNCC[C@@H](C1=CC=CS1)OC2=CC=CC3=CC=CC=C32
ELETRIPTAN HYDROBROMIDE
CN1CCC[C@@H]1CC2=CNC3=C2C=C(C=C3)CCS(=O)(=O)C4=CC=CC=C4
ENALAPRIL MALEATE
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2CCC[C@H]2C(=O)O
ENTACAPONE
CCN(CC)C(=O)/C(=C/C1=CC(=C(C(=C1)O)O)[N+](=O)[O-])/C#N
ERGONOVINE MALEATE
C[C@@H](CO)NC(=O)[C@H]1CN([C@@H]2CC3=CNC4=CC=CC(=C34)C2=C1)C
ERGOTAMINE TARTRATE
C[C@@]1(C(=O)N2[C@H](C(=O)N3CCC[C@H]3[C@@]2(O1)O)CC4=CC=CC=C4)NC(=O)[C@H]5CN([C@@H]6CC7=CNC8=CC=CC(=C78)C6=C5)C
ESZOPICLONE
CN1CCN(CC1)C(=O)O[C@H]2C3=NC=CN=C3C(=O)N2C4=NC=C(C=C4)Cl
ETHOPROPAZINE
CCN(CC)C(C)CN1C2=CC=CC=C2SC3=CC=CC=C31
ETHOXZOLAMIDE
CCOC1=CC2=C(C=C1)N=C(S2)S(=O)(=O)N
ETHYNODIOL DIACETATE
CC(=O)O[C@H]1CC[C@@H]2[C@H]3CC[C@]4([C@H]([C@@H]3CCC2=C1)CC[C@]4(C#C)OC(=O)C)C
ETODOLAC
CCC1=C2C(=CC=C1)C3=C(N2)C(OCC3)(CC)CC(=O)O
EZETIMIBE
C1=CC(=CC=C1[C@@H]2[C@H](C(=O)N2C3=CC=C(C=C3)F)CC[C@@H](C4=CC=C(C=C4)F)O)O
FAMCICLOVIR
CC(=O)OCC(CCN1C=NC2=CN=C(N=C21)N)COC(=O)C
FAMPROFAZONE
CC(C)C1=C(N(N(C1=O)C2=CC=CC=C2)C)CN(C)C(C)CC3=CC=CC=C3
FEBUXOSTAT
CC1=C(SC(=N1)C2=CC(=C(C=C2)OCC(C)C)C#N)C(=O)O
FENOFIBRATE
CC(C)OC(=O)C(C)(C)OC1=CC=C(C=C1)C(=O)C2=CC=C(C=C2)Cl
FENSPIRIDE
C1CN(CCC12CNC(=O)O2)CCC3=CC=CC=C3
FEXOFENADINE
CC(C)(C1=CC=C(C=C1)C(CCCN2CCC(CC2)C(C3=CC=CC=C3)(C4=CC=CC=C4)O)O)C(=O)O
FINASTERIDE
C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2C(=O)NC(C)(C)C)CC[C@@H]4[C@@]3(C=CC(=O)N4)C
FLUCONAZOLE
C1=CC(=C(C=C1F)F)C(CN2C=NC=N2)(CN3C=NC=N3)O
FLUOXETINE
CNCCC(C1=CC=CC=C1)OC2=CC=C(C=C2)C(F)(F)F
FLUPHENAZINE
C1CN(CCN1CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)C(F)(F)F)CCO
FLUVOXAMINE MALEATE
COCCCC/C(=N/OCCN)/C1=CC=C(C=C1)C(F)(F)F
GALANTAMINE
CN1CC[C@@]23C=C[C@@H](C[C@@H]2OC4=C(C=CC(=C34)C1)OC)O
GLICLAZIDE
CC1=CC=C(C=C1)S(=O)(=O)NC(=O)NN2CC3CCCC3C2
GLIPIZIDE
CC1=CN=C(C=N1)C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)NC(=O)NC3CCCCC3
GRISEOFULVIN
C[C@@H]1CC(=O)C=C([C@]12C(=O)C3=C(O2)C(=C(C=C3OC)OC)Cl)OC
GUANFACINE
C1=CC(=C(C(=C1)Cl)CC(=O)N=C(N)N)Cl
HALOPERIDOL
C1CN(CCC1(C2=CC=C(C=C2)Cl)O)CCCC(=O)C3=CC=C(C=C3)F
HYOSCYAMINE
CN1[C@H]2CCC1CC(C2)OC(=O)[C@H](CO)C3=CC=CC=C3
IDEBENONE
CC1=C(C(=O)C(=C(C1=O)OC)OC)CCCCCCCCCCO
IMATINIB
CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5
INDAPAMIDE
CC1CC2=CC=CC=C2N1NC(=O)C3=CC(=C(C=C3)Cl)S(=O)(=O)N
INDOMETHACIN
CC1=C(C2=C(N1C(=O)C3=CC=C(C=C3)Cl)C=CC(=C2)OC)CC(=O)O
IRBESARTAN
CCCCC1=NC2(CCCC2)C(=O)N1CC3=CC=C(C=C3)C4=CC=CC=C4C5=NNN=N5
IRSOGLADINE MALEATE
C1=CC(=C(C=C1Cl)C2=NC(=NC(=N2)N)N)Cl
ISRADIPINE
CC1=C(C(C(=C(N1)C)C(=O)OC(C)C)C2=CC=CC3=NON=C32)C(=O)OC
ITRACONAZOLE
CCC(C)N1C(=O)N(C=N1)C2=CC=C(C=C2)N3CCN(CC3)C4=CC=C(C=C4)OCC5CO[C@](O5)(CN6C=NC=N6)C7=C(C=C(C=C7)Cl)Cl
KETOROLAC TROMETHAMINE
C1CN2C(=CC=C2C(=O)C3=CC=CC=C3)C1C(=O)O
KETOTIFEN FUMARATE
CN1CCC(=C2C3=C(C(=O)CC4=CC=CC=C42)SC=C3)CC1
LABETALOL
CC(CCC1=CC=CC=C1)NCC(C2=CC(=C(C=C2)O)C(=O)N)O
LAMOTRIGINE
C1=CC(=C(C(=C1)Cl)Cl)C2=C(N=C(N=N2)N)N
LETROZOLE
C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3
LEVAMISOLE
C1CSC2=N[C@H](CN21)C3=CC=CC=C3
LEVONORGESTREL
CC[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C#C)O)CCC4=CC(=O)CC[C@H]34
LINAGLIPTIN
CC#CCN1C2=C(N=C1N3CCC[C@H](C3)N)N(C(=O)N(C2=O)CC4=NC5=CC=CC=C5C(=N4)C)C
LOFEXIDINE
CC(C1=NCCN1)OC2=C(C=CC=C2Cl)Cl
LOPERAMIDE
CN(C)C(=O)C(CCN1CCC(CC1)(C2=CC=C(C=C2)Cl)O)(C3=CC=CC=C3)C4=CC=CC=C4
LOSARTAN
CCCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NNN=N4)CO)Cl
LOVASTATIN
CC[C@H](C)C(=O)O[C@H]1C[C@H](C=C2[C@H]1[C@H]([C@H](C=C2)C)CC[C@@H]3C[C@H](CC(=O)O3)O)C
LOXAPINE SUCCINATE
CN1CCN(CC1)C2=NC3=CC=CC=C3OC4=C2C=C(C=C4)Cl
MEBENDAZOLE
COC(=O)NC1=NC2=C(N1)C=C(C=C2)C(=O)C3=CC=CC=C3
MEBHYDROLIN NAPHTHALENESULFONATE
C1=CC2=C(C=CC=C2S(=O)(=O)O)C(=C1)S(=O)(=O)O
MEFLOQUINE
C1CCNC(C1)[C@H](C2=CC(=NC3=C2C=CC=C3C(F)(F)F)C(F)(F)F)O
MEGESTROL ACETATE
CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC[C@@]3(C(=O)C)OC(=O)C)C)[C@@]4(C1=CC(=O)CC4)C
MELPHALAN
C1=CC(=CC=C1C[C@@H](C(=O)O)N)N(CCCl)CCCl
MEMANTINE
CC12CC3CC(C1)(CC(C3)(C2)N)C
METAXALONE
CC1=CC(=CC(=C1)OCC2CNC(=O)O2)C
METHOCARBAMOL
COC1=CC=CC=C1OCC(COC(=O)N)O
METHOXSALEN
COC1=C2C(=CC3=C1OC=C3)C=CC(=O)O2
METHSUXIMIDE
CC1(CC(=O)N(C1=O)C)C2=CC=CC=C2
METHYLPHENIDATE
COC(=O)C(C1CCCCN1)C2=CC=CC=C2
METHYSERGIDE MALEATE
CC[C@@H](CO)NC(=O)[C@H]1CN([C@@H]2CC3=CN(C4=CC=CC(=C34)C2=C1)C)C
METICRANE
CC1=CC2=C(C=C1S(=O)(=O)N)S(=O)(=O)CCC2
METITEPINE MALEATE
CN1CCN(CC1)C2CC3=CC=CC=C3SC4=C2C=C(C=C4)SC
METOCLOPRAMIDE
CCN(CC)CCNC(=O)C1=CC(=C(C=C1OC)N)Cl
METOLAZONE
CC1NC2=CC(=C(C=C2C(=O)N1C3=CC=CC=C3C)S(=O)(=O)N)Cl
METOPROLOL TARTRATE
CC(C)NCC(COC1=CC=C(C=C1)CCOC)O
MEVASTATIN
CC[C@H](C)C(=O)O[C@H]1CCC=C2[C@H]1[C@H]([C@H](C=C2)C)CC[C@@H]3C[C@H](CC(=O)O3)O
MIANSERIN
CN1CCN2C(C1)C3=CC=CC=C3CC4=CC=CC=C42
MIFEPRISTONE
CC#C[C@@]1(CC[C@@H]2[C@@]1(C[C@@H](C3=C4CCC(=O)C=C4CC[C@@H]23)C5=CC=C(C=C5)N(C)C)C)O
MILNACIPRAN
CCN(CC)C(=O)[C@@]1(C[C@@H]1CN)C2=CC=CC=C2
MYCOPHENOLATE MOFETIL
CC1=C2COC(=O)C2=C(C(=C1OC)C/C=C(\C)/CCC(=O)OCCN3CCOCC3)O
NADOLOL
CC(C)(C)NCC(COC1=CC=CC2=C1C[C@@H]([C@@H](C2)O)O)O
NAFRONYL OXALATE
CCN(CC)CCOC(=O)C(CC1CCCO1)CC2=CC=CC3=CC=CC=C32
NAFTOPIDIL
COC1=CC=CC=C1N2CCN(CC2)CC(COC3=CC=CC4=CC=CC=C43)O
NALOXONE
C=CCN1CC[C@]23[C@@H]4C(=O)CC[C@]2([C@H]1CC5=C3C(=C(C=C5)O)O4)O
NAPROXEN
C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O
NATEGLINIDE
CC(C)C1CCC(CC1)C(=O)N[C@H](CC2=CC=CC=C2)C(=O)O
NEFAZODONE
CCC1=NN(C(=O)N1CCOC2=CC=CC=C2)CCCN3CCN(CC3)C4=CC(=CC=C4)Cl
NEFOPAM
CN1CCOC(C2=CC=CC=C2C1)C3=CC=CC=C3
NEOSTIGMINE BROMIDE
CN(C)C(=O)OC1=CC=CC(=C1)[N+](C)(C)C
NEVIRAPINE
CC1=C2C(=NC=C1)N(C3=C(C=CC=N3)C(=O)N2)C4CC4
NICERGOLINE
CN1C[C@@H](C[C@]2([C@H]1CC3=CN(C4=CC=CC2=C34)C)OC)COC(=O)C5=CC(=CN=C5)Br
NITRENDIPINE
CCOC(=O)C1=C(NC(=C(C1C2=CC(=CC=C2)[N+](=O)[O-])C(=O)OC)C)C
NIZATIDINE
CN/C(=C\[N+](=O)[O-])/NCCSCC1=CSC(=N1)CN(C)C
NORETHINDRONE ACETATE
CC(=O)O[C@]1(CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4=CC(=O)CC[C@H]34)C)C#C
NORGESTIMATE
CC[C@@]12CC[C@@H]3[C@@H]([C@H]1CC[C@@]2(C#C)OC(=O)C)CCC4=C/C(=N/O)/CC[C@@H]34
NOSCAPINE
CN1CCC2=CC3=C(C(=C2[C@@H]1[C@@H]4C5=C(C(=C(C=C5)OC)OC)C(=O)O4)OC)OCO3
OLANZAPINE
CC1=CC2=C(S1)NC3=CC=CC=C3N=C2N4CCN(CC4)C
OLMESARTAN MEDOXOMIL
CCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NNN=N4)C(=O)OCC5=C(OC(=O)O5)C)C(C)(C)O
OMEPRAZOLE
CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC
ORPHENADRINE CITRATE
CC1=CC=CC=C1C(C2=CC=CC=C2)OCCN(C)C
OXAPROZIN
C1=CC=C(C=C1)C2=C(OC(=N2)CCC(=O)O)C3=CC=CC=C3
OXCARBAZEPINE
C1C2=CC=CC=C2N(C3=CC=CC=C3C1=O)C(=O)N
OXETHAZAINE
CC(C)(CC1=CC=CC=C1)N(C)C(=O)CN(CCO)CC(=O)N(C)C(C)(C)CC2=CC=CC=C2
OXYBUTYNIN CHLORIDE
CCN(CC)CC#CCOC(=O)C(C1CCCCC1)(C2=CC=CC=C2)O
PACLITAXEL
CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@H]3[C@@H]([C@@](C2(C)C)(C[C@@H]1OC(=O)[C@@H]([C@H](C5=CC=CC=C5)NC(=O)C6=CC=CC=C6)O)O)OC(=O)C7=CC=CC=C7)(CO4)OC(=O)C)O)C)OC(=O)C
PALIPERIDONE
CC1=C(C(=O)N2CCCC(C2=N1)O)CCN3CCC(CC3)C4=NOC5=C4C=CC(=C5)F
PANTOPRAZOLE
COC1=C(C(=NC=C1)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC(F)F)OC
PAPAVERINE
COC1=C(C=C(C=C1)CC2=NC=CC3=CC(=C(C=C32)OC)OC)OC
PAROXETINE
C1CNC[C@H]([C@@H]1C2=CC=C(C=C2)F)COC3=CC4=C(C=C3)OCO4
PENBUTOLOL SULFATE
CC(C)(C)NC[C@@H](COC1=CC=CC=C1C2CCCC2)O
PENTOXIFYLLINE
CC(=O)CCCCN1C(=O)C2=C(N=CN2C)N(C1=O)C
PERGOLIDE MESYLATE
CCCN1C[C@@H](C[C@H]2[C@H]1CC3=CNC4=CC=CC2=C34)CSC
PERICYAZINE
C1CN(CCC1O)CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)C#N
PERINDOPRIL ERBUMINE
CCC[C@@H](C(=O)OCC)N[C@@H](C)C(=O)N1[C@H]2CCCC[C@H]2C[C@H]1C(=O)O
PHENACETIN
CCOC1=CC=C(C=C1)NC(=O)C
PHENAZOPYRIDINE
C1=CC=C(C=C1)N=NC2=C(N=C(C=C2)N)N
PHENYTOIN SODIUM
C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3
PIDOTIMOD
C1CC(=O)N[C@@H]1C(=O)N2CSC[C@H]2C(=O)O
PIMOZIDE
C1CN(CCC1N2C3=CC=CC=C3NC2=O)CCCC(C4=CC=C(C=C4)F)C5=CC=C(C=C5)F
PITAVASTATIN CALCIUM
C1CC1C2=NC3=CC=CC=C3C(=C2/C=C/[C@H](C[C@H](CC(=O)O)O)O)C4=CC=C(C=C4)F
PRANOPROFEN
CC(C1=CC2=C(C=C1)OC3=C(C2)C=CC=N3)C(=O)O
PRAZOSIN
COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4=CC=CO4)N)OC
PREDNISONE
C[C@]12CC(=O)[C@H]3[C@H]([C@@H]1CC[C@@]2(C(=O)CO)O)CCC4=CC(=O)C=C[C@]34C
PRIDINOL METHANESULFONATE
C1CCN(CC1)CCC(C2=CC=CC=C2)(C3=CC=CC=C3)O
PRIMAQUINE PHOSPHATE
CC(CCCN)NC1=C2C(=CC(=C1)OC)C=CC=N2
PROCARBAZINE
CC(C)NC(=O)C1=CC=C(C=C1)CNNC
PROMETHAZINE
CC(CN1C2=CC=CC=C2SC3=CC=CC=C31)N(C)C
PYRIMETHAMINE
CCC1=C(C(=NC(=N1)N)N)C2=CC=C(C=C2)Cl
QUETIAPINE
C1CN(CCN1CCOCCO)C2=NC3=CC=CC=C3SC4=CC=CC=C42
QUINAPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2CC3=CC=CC=C3C[C@H]2C(=O)O
QUININE SULFATE
COC1=CC2=C(C=CN=C2C=C1)[C@H]([C@@H]3C[C@@H]4CCN3C[C@@H]4C=C)O
RACECADOTRIL
CC(=O)SCC(CC1=CC=CC=C1)C(=O)NCC(=O)OCC2=CC=CC=C2
RAMELTEON
CCC(=O)NCC[C@@H]1CCC2=C1C3=C(C=C2)OCC3
RAMIPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2[C@H]3CCC[C@H]3C[C@H]2C(=O)O
RANITIDINE
CN/C(=C\[N+](=O)[O-])/NCCSCC1=CC=C(O1)CN(C)C
RANOLAZINE
CC1=C(C(=CC=C1)C)NC(=O)CN2CCN(CC2)CC(COC3=CC=CC=C3OC)O
REBAMIPIDE
C1=CC=C2C(=C1)C(=CC(=O)N2)CC(C(=O)O)NC(=O)C3=CC=C(C=C3)Cl
REPAGLINIDE
CCOC1=C(C=CC(=C1)CC(=O)N[C@@H](CC(C)C)C2=CC=CC=C2N3CCCCC3)C(=O)O
RESERPINE
CO[C@H]1[C@@H](C[C@@H]2CN3CCC4=C([C@H]3C[C@@H]2[C@@H]1C(=O)OC)NC5=C4C=CC(=C5)OC)OC(=O)C6=CC(=C(C(=C6)OC)OC)OC
RILUZOLE
C1=CC2=C(C=C1OC(F)(F)F)SC(=N2)N
RIMANTADINE
CC(C12CC3CC(C1)CC(C3)C2)N
RISPERIDONE
CC1=C(C(=O)N2CCCCC2=N1)CCN3CCC(CC3)C4=NOC5=C4C=CC(=C5)F
RITONAVIR
CC(C)C1=NC(=CS1)CN(C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CC2=CC=CC=C2)C[C@@H]([C@H](CC3=CC=CC=C3)NC(=O)OCC4=CN=CS4)O
RIVASTIGMINE TARTRATE
CCN(C)C(=O)OC1=CC=CC(=C1)C(C)N(C)C
RIZATRIPTAN BENZOATE
CN(C)CCC1=CNC2=C1C=C(C=C2)CN3C=NC=N3
ROPINIROLE
CCCN(CCC)CCC1=C2CC(=O)NC2=CC=C1
ROSIGLITAZONE MALEATE
CN(CCOC1=CC=C(C=C1)CC2C(=O)NC(=O)S2)C3=CC=CC=N3
ROSUVASTATIN CALCIUM
CC(C)C1=NC(=NC(=C1/C=C/[C@H](C[C@H](CC(=O)O)O)O)C2=CC=C(C=C2)F)N(C)S(=O)(=O)C
ROXATIDINE ACETATE
CC(=O)OCC(=O)NCCCOC1=CC=CC(=C1)CN2CCCCC2
SERTRALINE
CN[C@H]1CC[C@H](C2=CC=CC=C12)C3=CC(=C(C=C3)Cl)Cl
SILDENAFIL CITRATE
CCCC1=NN(C2=C1N=C(NC2=O)C3=C(C=CC(=C3)S(=O)(=O)N4CCN(CC4)C)OCC)C
SOLIFENACIN SUCCINATE
C1CN2CCC1[C@H](C2)OC(=O)N3CCC4=CC=CC=C4[C@@H]3C5=CC=CC=C5
SOTALOL
CC(C)NCC(C1=CC=C(C=C1)NS(=O)(=O)C)O
SPIPERONE
C1CN(CCC12C(=O)NCN2C3=CC=CC=C3)CCCC(=O)C4=CC=C(C=C4)F
SULFASALAZINE
C1=CC=NC(=C1)NS(=O)(=O)C2=CC=C(C=C2)N=NC3=CC(=C(C=C3)O)C(=O)O
SULFINPYRAZONE
C1=CC=C(C=C1)N2C(=O)C(C(=O)N2C3=CC=CC=C3)CCS(=O)C4=CC=CC=C4
SULINDAC
CC\1=C(C2=C(/C1=C\C3=CC=C(C=C3)S(=O)C)C=CC(=C2)F)CC(=O)O
SULPIRIDE
CCN1CCCC1CNC(=O)C2=C(C=CC(=C2)S(=O)(=O)N)OC
SUMATRIPTAN SUCCINATE
CNS(=O)(=O)CC1=CC2=C(C=C1)NC=C2CCN(C)C
TACRINE
C1CCC2=NC3=CC=CC=C3C(=C2C1)N
TACROLIMUS
C[C@@H]1C[C@@H]([C@@H]2[C@H](C[C@H]([C@@](O2)(C(=O)C(=O)N3CCCC[C@H]3C(=O)O[C@@H]([C@@H]([C@H](CC(=O)[C@@H](/C=C(/C1)\C)CC=C)O)C)/C(=C/[C@@H]4CC[C@H]([C@@H](C4)OC)O)/C)O)C)OC)OC
TADALAFIL
CN1CC(=O)N2[C@@H](C1=O)CC3=C([C@H]2C4=CC5=C(C=C4)OCO5)NC6=CC=CC=C36
TAMSULOSIN HYDRCHLORIDE
CCOC1=CC=CC=C1OCCN[C@H](C)CC2=CC(=C(C=C2)OC)S(=O)(=O)N
TEGASEROD MALEATE
CCCCCN=C(N)N/N=C\C1=CNC2=C1C=C(C=C2)OC
TELMISARTAN
CCCC1=NC2=C(N1CC3=CC=C(C=C3)C4=CC=CC=C4C(=O)O)C=C(C=C2C)C5=NC6=CC=CC=C6N5C
TENATOPRAZOLE
CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=CC(=N3)OC
TENOXICAM
CN1C(=C(C2=C(S1(=O)=O)C=CS2)O)C(=O)NC3=CC=CC=N3
TERAZOSIN
COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4CCCO4)N)OC
TERBINAFINE
CC(C)(C)C#C/C=C/CN(C)CC1=CC=CC2=CC=CC=C21
THIABENDAZOLE
C1=CC=C2C(=C1)NC(=N2)C3=CSC=N3
THIOTHIXENE
CN1CCN(CC1)CCC=C2C3=CC=CC=C3SC4=C2C=C(C=C4)S(=O)(=O)N(C)C
TIAPRIDE
CCN(CC)CCNC(=O)C1=C(C=CC(=C1)S(=O)(=O)C)OC
TIMOLOL MALEATE
CC(C)(C)NC[C@@H](COC1=NSN=C1N2CCOCC2)O
TINIDAZOLE
CCS(=O)(=O)CCN1C(=NC=C1[N+](=O)[O-])C
TOLAZAMIDE
CC1=CC=C(C=C1)S(=O)(=O)NC(=O)NN2CCCCCC2
TOPOTECAN
CC[C@@]1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5CN(C)C)O)N=C4C3=C2)O
TRANDOLAPRIL
CCOC(=O)[C@H](CCC1=CC=CC=C1)N[C@@H](C)C(=O)N2[C@H]3CCCC[C@@H]3C[C@H]2C(=O)O
TRANILAST
COC1=C(C=C(C=C1)/C=C/C(=O)NC2=CC=CC=C2C(=O)O)OC
TRAZODONE
C1CN(CCN1CCCN2C(=O)N3C=CC=CC3=N2)C4=CC(=CC=C4)Cl
TRIHEXYPHENIDYL
C1CCC(CC1)C(CCN2CCCCC2)(C3=CC=CC=C3)O
TRIMEBUTINE MALEATE
CCC(COC(=O)C1=CC(=C(C(=C1)OC)OC)OC)(C2=CC=CC=C2)N(C)C
TRIMETAZIDINE
COC1=C(C(=C(C=C1)CN2CCNCC2)OC)OC
TRIMETHOBENZAMIDE
CN(C)CCOC1=CC=C(C=C1)CNC(=O)C2=CC(=C(C(=C2)OC)OC)OC
TRIMIPRAMINE MALEATE
CC(CN1C2=CC=CC=C2CCC3=CC=CC=C31)CN(C)C
TRIPROLIDINE
CC1=CC=C(C=C1)/C(=C\CN2CCCC2)/C3=CC=CC=N3
TROPISETRON
CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C3=CNC4=CC=CC=C43
VALSARTAN
CCCCC(=O)N(CC1=CC=C(C=C1)C2=CC=CC=C2C3=NNN=N3)[C@@H](C(C)C)C(=O)O
VENLAFAXINE
CN(C)CC(C1=CC=C(C=C1)OC)C2(CCCCC2)O
VERAPAMIL
CC(C)C(CCCN(C)CCC1=CC(=C(C=C1)OC)OC)(C#N)C2=CC(=C(C=C2)OC)OC
VILAZODONE
C1CN(CCN1CCCCC2=CNC3=C2C=C(C=C3)C#N)C4=CC5=C(C=C4)OC(=C5)C(=O)N
VINPOCETINE
CC[C@@]12CCCN3[C@@H]1C4=C(CC3)C5=CC=CC=C5N4C(=C2)C(=O)OCC
VORICONAZOLE
C[C@@H](C1=NC=NC=C1F)[C@](CN2C=NC=N2)(C3=C(C=C(C=C3)F)F)O
WARFARIN
CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O
ZALEPLON
CCN(C1=CC=CC(=C1)C2=CC=NC3=C(C=NN23)C#N)C(=O)C
ZIDOVUDINE  AZT
CC1=CN(C(=O)NC1=O)[C@H]2C[C@@H]([C@H](O2)CO)N=[N+]=[N-]
ZIPRASIDONE MESYLATE
C1CN(CCN1CCC2=C(C=C3C(=C2)CC(=O)N3)Cl)C4=NSC5=CC=CC=C54
ZOLPIDEM
CC1=CC=C(C=C1)C2=C(N3C=C(C=CC3=N2)C)CC(=O)N(C)C
BETAMETHASONE
C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]3([C@H](C[C@@]2([C@]1(C(=O)CO)O)C)O)F)C
DIHYDROERGOTAMINE MESYLATE
C[C@@]1(C(=O)N2[C@H](C(=O)N3CCC[C@H]3[C@@]2(O1)O)CC4=CC=CC=C4)NC(=O)[C@@H]5C[C@H]6[C@@H](CC7=CNC8=CC=CC6=C78)N(C5)C
MESORIDAZINE BESYLATE
CN1CCCCC1CCN2C3=CC=CC=C3SC4=C2C=C(C=C4)S(=O)C
ARIPIPRAZOLE
C1CC(=O)NC2=C1C=CC(=C2)OCCCCN3CCN(CC3)C4=C(C(=CC=C4)Cl)Cl
PROCHLORPERAZINE EDISYLATE
CN1CCN(CC1)CCCN2C3=CC=CC=C3SC4=C2C=C(C=C4)Cl

In [276]:
salt_names = ["CALCIUM", "PHOSPHATE", "SULFATE", "MALEATE", "FUMARATE", "MESYLATE", "CITRATE", "HYDROBROMIDE", "BROMIDE", "SUCCINATE", "TARTRATE", "TROMETHAMINE", 
"OXALATE", "CHLORIDE", "ERBUMINE", "SODIUM", "METHANESULFONATE", "BENZOATE", "HYDRCHLORIDE", "BESYLATE", "EDISYLATE"]

In [277]:
for i, row in frame.iterrows():
    found_elements = [element for element in salt_names if element in frame["ID_pubchem"][i]]
    stringuse = str(frame["ID_pubchem"][i])
    if len(found_elements)>1:
        found_elements = max(found_elements, key=len)
        frame["ID_pubchem"][i] = stringuse.replace(found_elements, "").strip()
    elif len(found_elements) == 1: 
        frame["ID_pubchem"][i] = stringuse.replace(found_elements[0], "").strip()

In [278]:
for i in frame["ID_pubchem"]:
    print(i)

BUDESONIDE
BUPROPION
BURAMATE
BUSPIRONE
ABACAVIR
ACEBUTOLOL
ACECAINIDE
ALFUZOSIN
ALMOTRIPTAN
ALPRENOLOL
AMANTADINE
AMINOGLUTETHIMIDE
AMISULPRIDE
ANAGRELIDE
ANASTROZOLE
ANTAZOLINE
APOMORPHINE
ARTEMISININ
ATENOLOL
ATORVASTATIN
AZATADINE
BAMBUTEROL
BENAZEPRIL
BENZBROMARONE
BENZTHIAZIDE
BETAMETHASONE ACETATE
BETAMETHASONE VALERATE
BETAXALOL
BEZAFIBRATE
BICALUTAMIDE
BIPERIDEN
BISACODYL
BISOPROLOL
BROMOCRIPTINE
BUDESONIDE
BUPROPION
BURAMATE
BUSPIRONE
CAMYLOFINE
CAPECITABINE
CARBETAPENTANE
CARBINOXAMINE
CARISOPRODOL
CARVEDILOL
CELECOXIB
CETIRIZINE
CHLORMEZANONE
CIMETIDINE
CITALOPRAM
CLEMASTINE
CLEMIZOLE
CLENBUTEROL
CLIDINIUM
CLONIDINE
CLOPIDOGREL
CLOZAPINE
COLCHICINE
CYCLOBENZAPRINE
CYCLOPHOSPHAMIDE
CYPROTERONE ACETATE
DABIGATRAN ETEXILATE
DANAZOL
DARIFENACIN
DASATINIB
DEFLAZACORT
DESVENLAFAXINE
DEXAMETHASONE
DEXTROMETHORPHAN
DIACETAMATE
DICYCLOMINE
DIFLORASONE DIACETATE
DILTIAZEM
DIPERODON
DIPHENYLPYRALINE
DIPYRIDAMOLE
DISOPYRAMIDE
DOMPERIDONE
DOXAZOSIN
DOXEPIN
DOXYLAMINE
DROSPIRENONE
DULOXETINE
ELETRIPTAN
ENALAPRIL
ENTACAPONE
ERGONOVINE
ERGOTAMINE
ESZOPICLONE
ETHOPROPAZINE
ETHOXZOLAMIDE
ETHYNODIOL DIACETATE
ETODOLAC
EZETIMIBE
FAMCICLOVIR
FAMPROFAZONE
FEBUXOSTAT
FENOFIBRATE
FENSPIRIDE
FEXOFENADINE
FINASTERIDE
FLUCONAZOLE
FLUOXETINE
FLUPHENAZINE
FLUVOXAMINE
GALANTAMINE
GLICLAZIDE
GLIPIZIDE
GRISEOFULVIN
GUANFACINE
HALOPERIDOL
HYOSCYAMINE
IDEBENONE
IMATINIB
INDAPAMIDE
INDOMETHACIN
IRBESARTAN
IRSOGLADINE
ISRADIPINE
ITRACONAZOLE
KETOROLAC
KETOTIFEN
LABETALOL
LAMOTRIGINE
LETROZOLE
LEVAMISOLE
LEVONORGESTREL
LINAGLIPTIN
LOFEXIDINE
LOPERAMIDE
LOSARTAN
LOVASTATIN
LOXAPINE
MEBENDAZOLE
MEBHYDROLIN NAPHTHALENESULFONATE
MEFLOQUINE
MEGESTROL ACETATE
MELPHALAN
MEMANTINE
METAXALONE
METHOCARBAMOL
METHOXSALEN
METHSUXIMIDE
METHYLPHENIDATE
METHYSERGIDE
METICRANE
METITEPINE
METOCLOPRAMIDE
METOLAZONE
METOPROLOL
MEVASTATIN
MIANSERIN
MIFEPRISTONE
MILNACIPRAN
MYCOPHENOLATE MOFETIL
NADOLOL
NAFRONYL
NAFTOPIDIL
NALOXONE
NAPROXEN
NATEGLINIDE
NEFAZODONE
NEFOPAM
NEOSTIGMINE
NEVIRAPINE
NICERGOLINE
NITRENDIPINE
NIZATIDINE
NORETHINDRONE ACETATE
NORGESTIMATE
NOSCAPINE
OLANZAPINE
OLMESARTAN MEDOXOMIL
OMEPRAZOLE
ORPHENADRINE
OXAPROZIN
OXCARBAZEPINE
OXETHAZAINE
OXYBUTYNIN
PACLITAXEL
PALIPERIDONE
PANTOPRAZOLE
PAPAVERINE
PAROXETINE
PENBUTOLOL
PENTOXIFYLLINE
PERGOLIDE
PERICYAZINE
PERINDOPRIL
PHENACETIN
PHENAZOPYRIDINE
PHENYTOIN
PIDOTIMOD
PIMOZIDE
PITAVASTATIN
PRANOPROFEN
PRAZOSIN
PREDNISONE
PRIDINOL
PRIMAQUINE
PROCARBAZINE
PROMETHAZINE
PYRIMETHAMINE
QUETIAPINE
QUINAPRIL
QUININE
RACECADOTRIL
RAMELTEON
RAMIPRIL
RANITIDINE
RANOLAZINE
REBAMIPIDE
REPAGLINIDE
RESERPINE
RILUZOLE
RIMANTADINE
RISPERIDONE
RITONAVIR
RIVASTIGMINE
RIZATRIPTAN
ROPINIROLE
ROSIGLITAZONE
ROSUVASTATIN
ROXATIDINE ACETATE
SERTRALINE
SILDENAFIL
SOLIFENACIN
SOTALOL
SPIPERONE
SULFASALAZINE
SULFINPYRAZONE
SULINDAC
SULPIRIDE
SUMATRIPTAN
TACRINE
TACROLIMUS
TADALAFIL
TAMSULOSIN
TEGASEROD
TELMISARTAN
TENATOPRAZOLE
TENOXICAM
TERAZOSIN
TERBINAFINE
THIABENDAZOLE
THIOTHIXENE
TIAPRIDE
TIMOLOL
TINIDAZOLE
TOLAZAMIDE
TOPOTECAN
TRANDOLAPRIL
TRANILAST
TRAZODONE
TRIHEXYPHENIDYL
TRIMEBUTINE
TRIMETAZIDINE
TRIMETHOBENZAMIDE
TRIMIPRAMINE
TRIPROLIDINE
TROPISETRON
VALSARTAN
VENLAFAXINE
VERAPAMIL
VILAZODONE
VINPOCETINE
VORICONAZOLE
WARFARIN
ZALEPLON
ZIDOVUDINE  AZT
ZIPRASIDONE
ZOLPIDEM
BETAMETHASONE
DIHYDROERGOTAMINE
MESORIDAZINE
ARIPIPRAZOLE
PROCHLORPERAZINE

In [ ]:
# MEBHYDROLIN NAPHTHALENESULFONATE
# C1=CC2=C(C=CC=C2S(=O)(=O)O)C(=C1)S(=O)(=O)O 
# ZIDOVUDINE  AZT
# RIVASTIGMINE
# CCN(C)C(=O)OC1=CC=CC(=C1)[C@H](C)N(C)C

In [194]:
frame["ID_pubchem"][272] = "ZIDOVUDINE AZT"

In [280]:
frame["ID_pubchem"][268]= "ZIDOVUDINE"

In [284]:
frame[frame["ID_pubchem"] == "MEBHYDROLIN NAPHTHALENESULFONATE"]

,ID,ROMol,ID_pubchem,full_smiles,SMILES
133,MEBHYDROLIN_NAPHTHALENESULFONATE,<rdkit.Chem.rdchem.Mol object at 0x7fafbdf3d1c0>,MEBHYDROLIN NAPHTHALENESULFONATE,CN1CCC2=C(C1)C3=CC=CC=C3N2CC4=CC=CC=C4.C1=CC2=...,C1=CC2=C(C=CC=C2S(=O)(=O)O)C(=C1)S(=O)(=O)O

In [282]:
frame["SMILES"][217] = "CCN(C)C(=O)OC1=CC=CC(=C1)[C@H](C)N(C)C"

In [285]:
frame["ID_pubchem"][133] = "MEBHYDROLIN"

In [286]:
frame["SMILES"][133] = "CN1CCC2=C(C1)C3=CC=CC=C3N2CC4=CC=CC=C4"

In [287]:
frame["ROMol"] = [Chem.MolFromSmiles(i) for i in frame["SMILES"]]

In [290]:
len(frame)

276

In [291]:
prefix = "GMDM"
RIDX = "GutMicrobiome_DrugMetabolism"

In [292]:
RIDX = ", ".join(itertools.repeat("GutMicrobiome_DrugMetabolism", 276)).split(', ')
RIDX

['GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism',
 'GutMicrobiome_DrugMetabolism']

In [293]:
data_list = list(range(1,len(frame)+1))

In [294]:
data_list

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276]

In [295]:
CIDX = [prefix + str(item).zfill(4) for item in data_list]

In [296]:
frame["CIDX"] = CIDX

In [297]:
PandasTools.WriteSDF(frame, "/g/zimmermann/Members/zulfiqar/ZM000_PistoiaPrj/GutMicrobiome/check_COMPOUND_CTAB.sdf", properties=['CIDX'])

In [298]:
frame_record = frame

In [306]:
frame_record["COMPOUND_KEY"] = [f.replace("_", " ") for f in frame_record["COMPOUND_KEY"]]

In [307]:
for i in frame_record["COMPOUND_KEY"]:
    print(i)

BUDESONIDE
BUPROPION
BURAMATE
BUSPIRONE
ABACAVIR SULFATE
ACEBUTOLOL
ACECAINIDE
ALFUZOSIN
ALMOTRIPTAN
ALPRENOLOL
AMANTADINE
AMINOGLUTETHIMIDE
AMISULPRIDE
ANAGRELIDE
ANASTROZOLE
ANTAZOLINE PHOSPHATE
APOMORPHINE
ARTEMISININ
ATENOLOL
ATORVASTATIN CALCIUM
AZATADINE MALEATE
BAMBUTEROL
BENAZEPRIL
BENZBROMARONE
BENZTHIAZIDE
BETAMETHASONE ACETATE
BETAMETHASONE VALERATE
BETAXALOL
BEZAFIBRATE
BICALUTAMIDE
BIPERIDEN
BISACODYL
BISOPROLOL FUMARATE
BROMOCRIPTINE MESYLATE
BUDESONIDE
BUPROPION
BURAMATE
BUSPIRONE
CAMYLOFINE
CAPECITABINE
CARBETAPENTANE CITRATE
CARBINOXAMINE MALEATE
CARISOPRODOL
CARVEDILOL
CELECOXIB
CETIRIZINE
CHLORMEZANONE
CIMETIDINE
CITALOPRAM HYDROBROMIDE
CLEMASTINE FUMARATE
CLEMIZOLE
CLENBUTEROL
CLIDINIUM BROMIDE
CLONIDINE
CLOPIDOGREL SULFATE
CLOZAPINE
COLCHICINE
CYCLOBENZAPRINE
CYCLOPHOSPHAMIDE
CYPROTERONE ACETATE
DABIGATRAN ETEXILATE MESYLATE
DANAZOL
DARIFENACIN HYDROBROMIDE
DASATINIB
DEFLAZACORT
DESVENLAFAXINE SUCCINATE
DEXAMETHASONE
DEXTROMETHORPHAN HYDROBROMIDE
DIACETAMATE
DICYCLOMINE
DIFLORASONE DIACETATE
DILTIAZEM
DIPERODON
DIPHENYLPYRALINE
DIPYRIDAMOLE
DISOPYRAMIDE PHOSPHATE
DOMPERIDONE
DOXAZOSIN MESYLATE
DOXEPIN
DOXYLAMINE SUCCINATE
DROSPIRENONE
DULOXETINE
ELETRIPTAN HYDROBROMIDE
ENALAPRIL MALEATE
ENTACAPONE
ERGONOVINE MALEATE
ERGOTAMINE TARTRATE
ESZOPICLONE
ETHOPROPAZINE
ETHOXZOLAMIDE
ETHYNODIOL DIACETATE
ETODOLAC
EZETIMIBE
FAMCICLOVIR
FAMPROFAZONE
FEBUXOSTAT
FENOFIBRATE
FENSPIRIDE
FEXOFENADINE
FINASTERIDE
FLUCONAZOLE
FLUOXETINE
FLUPHENAZINE
FLUVOXAMINE MALEATE
GALANTAMINE
GLICLAZIDE
GLIPIZIDE
GRISEOFULVIN
GUANFACINE
HALOPERIDOL
HYOSCYAMINE
IDEBENONE
IMATINIB
INDAPAMIDE
INDOMETHACIN
IRBESARTAN
IRSOGLADINE MALEATE
ISRADIPINE
ITRACONAZOLE
KETOROLAC TROMETHAMINE
KETOTIFEN FUMARATE
LABETALOL
LAMOTRIGINE
LETROZOLE
LEVAMISOLE
LEVONORGESTREL
LINAGLIPTIN
LOFEXIDINE
LOPERAMIDE
LOSARTAN
LOVASTATIN
LOXAPINE SUCCINATE
MEBENDAZOLE
MEBHYDROLIN NAPHTHALENESULFONATE
MEFLOQUINE
MEGESTROL ACETATE
MELPHALAN
MEMANTINE
METAXALONE
METHOCARBAMOL
METHOXSALEN
METHSUXIMIDE
METHYLPHENIDATE
METHYSERGIDE MALEATE
METICRANE
METITEPINE MALEATE
METOCLOPRAMIDE
METOLAZONE
METOPROLOL TARTRATE
MEVASTATIN
MIANSERIN
MIFEPRISTONE
MILNACIPRAN
MYCOPHENOLATE MOFETIL
NADOLOL
NAFRONYL OXALATE
NAFTOPIDIL
NALOXONE
NAPROXEN
NATEGLINIDE
NEFAZODONE
NEFOPAM
NEOSTIGMINE BROMIDE
NEVIRAPINE
NICERGOLINE
NITRENDIPINE
NIZATIDINE
NORETHINDRONE ACETATE
NORGESTIMATE
NOSCAPINE
OLANZAPINE
OLMESARTAN MEDOXOMIL
OMEPRAZOLE
ORPHENADRINE CITRATE
OXAPROZIN
OXCARBAZEPINE
OXETHAZAINE
OXYBUTYNIN CHLORIDE
PACLITAXEL
PALIPERIDONE
PANTOPRAZOLE
PAPAVERINE
PAROXETINE
PENBUTOLOL SULFATE
PENTOXIFYLLINE
PERGOLIDE MESYLATE
PERICYAZINE
PERINDOPRIL ERBUMINE
PHENACETIN
PHENAZOPYRIDINE
PHENYTOIN SODIUM
PIDOTIMOD
PIMOZIDE
PITAVASTATIN CALCIUM
PRANOPROFEN
PRAZOSIN
PREDNISONE
PRIDINOL METHANESULFONATE
PRIMAQUINE PHOSPHATE
PROCARBAZINE
PROMETHAZINE
PYRIMETHAMINE
QUETIAPINE
QUINAPRIL
QUININE SULFATE
RACECADOTRIL
RAMELTEON
RAMIPRIL
RANITIDINE
RANOLAZINE
REBAMIPIDE
REPAGLINIDE
RESERPINE
RILUZOLE
RIMANTADINE
RISPERIDONE
RITONAVIR
RIVASTIGMINE TARTRATE
RIZATRIPTAN BENZOATE
ROPINIROLE
ROSIGLITAZONE MALEATE
ROSUVASTATIN CALCIUM
ROXATIDINE ACETATE
SERTRALINE
SILDENAFIL CITRATE
SOLIFENACIN SUCCINATE
SOTALOL
SPIPERONE
SULFASALAZINE
SULFINPYRAZONE
SULINDAC
SULPIRIDE
SUMATRIPTAN SUCCINATE
TACRINE
TACROLIMUS
TADALAFIL
TAMSULOSIN HYDRCHLORIDE
TEGASEROD MALEATE
TELMISARTAN
TENATOPRAZOLE
TENOXICAM
TERAZOSIN
TERBINAFINE
THIABENDAZOLE
THIOTHIXENE
TIAPRIDE
TIMOLOL MALEATE
TINIDAZOLE
TOLAZAMIDE
TOPOTECAN
TRANDOLAPRIL
TRANILAST
TRAZODONE
TRIHEXYPHENIDYL
TRIMEBUTINE MALEATE
TRIMETAZIDINE
TRIMETHOBENZAMIDE
TRIMIPRAMINE MALEATE
TRIPROLIDINE
TROPISETRON
VALSARTAN
VENLAFAXINE
VERAPAMIL
VILAZODONE
VINPOCETINE
VORICONAZOLE
WARFARIN
ZALEPLON
ZIDOVUDINE  AZT
ZIPRASIDONE MESYLATE
ZOLPIDEM
BETAMETHASONE
DIHYDROERGOTAMINE MESYLATE
MESORIDAZINE BESYLATE
ARIPIPRAZOLE
PROCHLORPERAZINE EDISYLATE

In [299]:
frame_record["RIDX"] = RIDX
frame_record["COMPOUND_NAME"] = frame["ID_pubchem"]
frame_record["COMPOUND_KEY"] = frame["ID"]

In [300]:
frame_record.columns

Index(['ID', 'ROMol', 'ID_pubchem', 'full_smiles', 'SMILES', 'CIDX', 'RIDX',
       'COMPOUND_NAME', 'COMPOUND_KEY'],
      dtype='object')

In [301]:
del frame_record["ID"]
del frame_record["ROMol"]
del frame_record["ID_pubchem"]
del frame_record["SMILES"]
del frame_record["full_smiles"]

In [308]:
frame_record[['CIDX', 'RIDX', 'COMPOUND_NAME', 'COMPOUND_KEY']]

,CIDX,RIDX,COMPOUND_NAME,COMPOUND_KEY
0,GMDM0001,GutMicrobiome_DrugMetabolism,BUDESONIDE,BUDESONIDE
1,GMDM0002,GutMicrobiome_DrugMetabolism,BUPROPION,BUPROPION
2,GMDM0003,GutMicrobiome_DrugMetabolism,BURAMATE,BURAMATE
3,GMDM0004,GutMicrobiome_DrugMetabolism,BUSPIRONE,BUSPIRONE
4,GMDM0005,GutMicrobiome_DrugMetabolism,ABACAVIR,ABACAVIR SULFATE
...,...,...,...,...
271,GMDM0272,GutMicrobiome_DrugMetabolism,BETAMETHASONE,BETAMETHASONE
272,GMDM0273,GutMicrobiome_DrugMetabolism,DIHYDROERGOTAMINE,DIHYDROERGOTAMINE MESYLATE
273,GMDM0274,GutMicrobiome_DrugMetabolism,MESORIDAZINE,MESORIDAZINE BESYLATE
274,GMDM0275,GutMicrobiome_DrugMetabolism,ARIPIPRAZOLE,ARIPIPRAZOLE
275,GMDM0276,GutMicrobiome_DrugMetabolism,PROCHLORPERAZINE,PROCHLORPERAZINE EDISYLATE

In [309]:
frame_record.to_csv("/g/zimmermann/Members/zulfiqar/ZM000_PistoiaPrj/GutMicrobiome/checkCOMPOUND_RECORD.tsv", sep ="\t")